/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Tina
 */
public class AddMedicationFrame extends javax.swing.JFrame {
	public static MainFrame mf;
    /**
     * Creates new form AddingMedFrame
     */
    public AddMedicationFrame(MainFrame mf) {
		this.mf = mf;
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        initComponents();
		AMF_TanSuatSuDung_JButton.setEnabled(false);
		this.setFrameInCenter();
        this.setVisible(true);
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }
    
    public int get_JPanel2_height() {
        return this.AMF_MocThoiGianSuDungThuoc_JPanel.getSize().height;
    }
    
    public int get_JPanel10_height() {
        return this.AMF_KhungNoiDungThemThuoc_JPanel.getSize().height;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AMF_ThanhChucNang_JPanel = new javax.swing.JPanel();
        AMF_Huy_JButton = new javax.swing.JButton();
        AMF_ThemDonThuocMoi_JLabel = new javax.swing.JLabel();
        AMF_Them_JButton = new javax.swing.JButton();
        AMF_NoiDungThemThuoc_JScrollPane = new javax.swing.JScrollPane();
        AMF_KhungNoiDungThemThuoc_JPanel = new javax.swing.JPanel();
        AMF_Ten_JPanel = new javax.swing.JPanel();
        AMF_Ten_JLabel = new javax.swing.JLabel();
        AMF_Ten_JTextField = new javax.swing.JTextField();
        AMF_DonVi_JPanel = new javax.swing.JPanel();
        AMF_DonVi_JLabel = new javax.swing.JLabel();
        AMF_DonVi_JTextField = new javax.swing.JTextField();
        AMF_GhiChu_JPanel = new javax.swing.JPanel();
        AMF_GhiChu_JLabel = new javax.swing.JLabel();
        AMF_GhiChu_JTextField = new javax.swing.JTextField();
        AMF_TanSuatSuDung_JPanel = new javax.swing.JPanel();
        AMF_TanSuatSuDung_JLabel = new javax.swing.JLabel();
        AMF_TanSuatSuDung_JComboBox = new javax.swing.JComboBox<>();
        AMF_TanSuatSuDung_JButton = new javax.swing.JButton();
        AMF_UuTienThongBao_JPanel = new javax.swing.JPanel();
        AMF_UuTienThongBao_JLabel = new javax.swing.JLabel();
        AMF_UuTienThongBao_JToggleButton = new javax.swing.JToggleButton();
        AMF_TuDongXacNhanSuDung_JPanel = new javax.swing.JPanel();
        AMF_TuDongXacNhanSuDung_JLabel = new javax.swing.JLabel();
        AMF_TuDongXacNhanSuDung_JToggleButton = new javax.swing.JToggleButton();
        AMF_KhoangThoiGianLapThongBao_JPanel = new javax.swing.JPanel();
        AMF_KhoangThoiGianLapThongBao_JLabel = new javax.swing.JLabel();
        AMF_KhoangThoiGianLapThongBao_JSpinner = new javax.swing.JSpinner();
        AMF_QuanLySoLuongThuoc_JPanel = new javax.swing.JPanel();
        AMF_QuanLySoLuongThuoc_JLabel = new javax.swing.JLabel();
        AMF_HienCo_JLabel = new javax.swing.JLabel();
        AMF_HienCo_JSpinner = new javax.swing.JSpinner();
        AMF_NhacNho_JLabel = new javax.swing.JLabel();
        AMF_NhacNho_JSpinner = new javax.swing.JSpinner();
        AMF_MocThoiGianSuDungThuoc_JPanel = new javax.swing.JPanel();
        AMF_MocThoiGianSuDungThuoc_Them_JButton = new javax.swing.JButton();
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner = new javax.swing.JSpinner();
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner = new javax.swing.JSpinner();
        AMF_AM_PM_JComboBox = new javax.swing.JComboBox<>();
        AMF_LieuSuDung_JLabel = new javax.swing.JLabel();
        AMF_LieuSuDung_JSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AMF_Huy_JButton.setFont(new java.awt.Font("SF Mono", 0, 24)); // NOI18N
        AMF_Huy_JButton.setText("Hủy");
        AMF_Huy_JButton.setMaximumSize(new java.awt.Dimension(90, 40));
        AMF_Huy_JButton.setMinimumSize(new java.awt.Dimension(90, 40));
        AMF_Huy_JButton.setPreferredSize(new java.awt.Dimension(90, 40));
        AMF_Huy_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Huy_JButtonActionPerformed(evt);
            }
        });
        AMF_ThanhChucNang_JPanel.add(AMF_Huy_JButton);

        AMF_ThemDonThuocMoi_JLabel.setFont(new java.awt.Font("SF Mono", 0, 36)); // NOI18N
        AMF_ThemDonThuocMoi_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AMF_ThemDonThuocMoi_JLabel.setText("Thêm đơn thuốc mới");
        AMF_ThemDonThuocMoi_JLabel.setPreferredSize(new java.awt.Dimension(480, 40));
        AMF_ThanhChucNang_JPanel.add(AMF_ThemDonThuocMoi_JLabel);

        AMF_Them_JButton.setFont(new java.awt.Font("SF Mono", 0, 24)); // NOI18N
        AMF_Them_JButton.setText("Thêm");
        AMF_Them_JButton.setMaximumSize(new java.awt.Dimension(90, 40));
        AMF_Them_JButton.setMinimumSize(new java.awt.Dimension(90, 40));
        AMF_Them_JButton.setPreferredSize(new java.awt.Dimension(90, 40));
        AMF_Them_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Them_JButtonActionPerformed(evt);
            }
        });
        AMF_ThanhChucNang_JPanel.add(AMF_Them_JButton);

        AMF_NoiDungThemThuoc_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AMF_NoiDungThemThuoc_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        AMF_KhungNoiDungThemThuoc_JPanel.setLayout(new java.awt.GridLayout(9, 1, 5, 5));

        AMF_Ten_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_Ten_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_Ten_JLabel.setText("Tên:");
        AMF_Ten_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JPanel.add(AMF_Ten_JLabel);

        AMF_Ten_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_Ten_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Ten_JTextFieldActionPerformed(evt);
            }
        });
        AMF_Ten_JPanel.add(AMF_Ten_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_Ten_JPanel);

        AMF_DonVi_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_DonVi_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_DonVi_JLabel.setText("Đơn vị:");
        AMF_DonVi_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JPanel.add(AMF_DonVi_JLabel);

        AMF_DonVi_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_DonVi_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JPanel.add(AMF_DonVi_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_DonVi_JPanel);

        AMF_GhiChu_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_GhiChu_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_GhiChu_JLabel.setText("Ghi chú:");
        AMF_GhiChu_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JPanel.add(AMF_GhiChu_JLabel);

        AMF_GhiChu_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_GhiChu_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JPanel.add(AMF_GhiChu_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_GhiChu_JPanel);

        AMF_TanSuatSuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_TanSuatSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_TanSuatSuDung_JLabel.setText("Tần suất sử dụng thuốc:");
        AMF_TanSuatSuDung_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JLabel);

        AMF_TanSuatSuDung_JComboBox.setFont(new java.awt.Font("SF Mono", 0, 16)); // NOI18N
        AMF_TanSuatSuDung_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mỗi ngày", "Ngày trong tuần", "Ngày trong tháng", "Khi cần thiết" }));
        AMF_TanSuatSuDung_JComboBox.setMaximumSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.setMinimumSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.setPreferredSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AMF_TanSuatSuDung_JComboBoxItemStateChanged(evt);
            }
        });
        AMF_TanSuatSuDung_JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_TanSuatSuDung_JComboBoxActionPerformed(evt);
            }
        });
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JComboBox);

        AMF_TanSuatSuDung_JButton.setText("...");
        AMF_TanSuatSuDung_JButton.setMaximumSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.setMinimumSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.setPreferredSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_TanSuatSuDung_JButtonActionPerformed(evt);
            }
        });
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_TanSuatSuDung_JPanel);

        AMF_UuTienThongBao_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_UuTienThongBao_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_UuTienThongBao_JLabel.setText("Đặt mức độ ưu tiên thông báo cao hơn:");
        AMF_UuTienThongBao_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JPanel.add(AMF_UuTienThongBao_JLabel);

        AMF_UuTienThongBao_JToggleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AMF_UuTienThongBao_JToggleButton.setText("Y/N");
        AMF_UuTienThongBao_JToggleButton.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_UuTienThongBao_JToggleButtonActionPerformed(evt);
            }
        });
        AMF_UuTienThongBao_JPanel.add(AMF_UuTienThongBao_JToggleButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_UuTienThongBao_JPanel);

        AMF_TuDongXacNhanSuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_TuDongXacNhanSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_TuDongXacNhanSuDung_JLabel.setText("Tự động xác nhận sử dụng thuốc:");
        AMF_TuDongXacNhanSuDung_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JPanel.add(AMF_TuDongXacNhanSuDung_JLabel);

        AMF_TuDongXacNhanSuDung_JToggleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AMF_TuDongXacNhanSuDung_JToggleButton.setText("Y/N");
        AMF_TuDongXacNhanSuDung_JToggleButton.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed(evt);
            }
        });
        AMF_TuDongXacNhanSuDung_JPanel.add(AMF_TuDongXacNhanSuDung_JToggleButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_TuDongXacNhanSuDung_JPanel);

        AMF_KhoangThoiGianLapThongBao_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_KhoangThoiGianLapThongBao_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_KhoangThoiGianLapThongBao_JLabel.setText("Khoảng thời gian lặp thông báo: ");
        AMF_KhoangThoiGianLapThongBao_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JPanel.add(AMF_KhoangThoiGianLapThongBao_JLabel);

        AMF_KhoangThoiGianLapThongBao_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_KhoangThoiGianLapThongBao_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setFocusable(false);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setRequestFocusEnabled(false);
        AMF_KhoangThoiGianLapThongBao_JPanel.add(AMF_KhoangThoiGianLapThongBao_JSpinner);
        JComponent editor_js10 = AMF_KhoangThoiGianLapThongBao_JSpinner.getEditor();
        JFormattedTextField tf_js10 = ((JSpinner.DefaultEditor) editor_js10).getTextField();
        tf_js10.setEditable(false);
        tf_js10.setColumns(3);
        tf_js10.setHorizontalAlignment(JTextField.CENTER);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_KhoangThoiGianLapThongBao_JPanel);

        AMF_QuanLySoLuongThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_QuanLySoLuongThuoc_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_QuanLySoLuongThuoc_JLabel.setText("Quản lý số lượng thuốc:");
        AMF_QuanLySoLuongThuoc_JLabel.setMaximumSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JLabel.setMinimumSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JLabel.setPreferredSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_QuanLySoLuongThuoc_JLabel);

        AMF_HienCo_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_HienCo_JLabel.setText("Hiện có");
        AMF_HienCo_JLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_HienCo_JLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_HienCo_JLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_HienCo_JLabel);

        AMF_HienCo_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_HienCo_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_HienCo_JSpinner.setFocusable(false);
        AMF_HienCo_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setRequestFocusEnabled(false);
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_HienCo_JSpinner);
        JComponent editor_js11 = AMF_HienCo_JSpinner.getEditor();
        JFormattedTextField tf_js11 = ((JSpinner.DefaultEditor) editor_js11).getTextField();
        tf_js11.setEditable(false);
        tf_js11.setColumns(3);
        tf_js11.setHorizontalAlignment(JTextField.CENTER);
        AMF_HienCo_JSpinner.setSize(64, 32);

        AMF_NhacNho_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_NhacNho_JLabel.setText("Nhắc nhở");
        AMF_NhacNho_JLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_NhacNho_JLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_NhacNho_JLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_NhacNho_JLabel);

        AMF_NhacNho_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_NhacNho_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_NhacNho_JSpinner.setFocusable(false);
        AMF_NhacNho_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setRequestFocusEnabled(false);
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_NhacNho_JSpinner);
        JComponent editor_js12 = AMF_NhacNho_JSpinner.getEditor();
        JFormattedTextField tf_js12 = ((JSpinner.DefaultEditor) editor_js12).getTextField();
        tf_js12.setEditable(false);
        tf_js12.setColumns(3);
        tf_js12.setHorizontalAlignment(JTextField.CENTER);
        AMF_NhacNho_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_QuanLySoLuongThuoc_JPanel);

        AMF_MocThoiGianSuDungThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_MocThoiGianSuDungThuoc_Them_JButton.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setText("Thêm");
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked(evt);
            }
        });
        AMF_MocThoiGianSuDungThuoc_Them_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_MocThoiGianSuDungThuoc_Them_JButtonActionPerformed(evt);
            }
        });
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Them_JButton);

        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setFocusable(false);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setRequestFocusEnabled(false);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Gio_JSpinner);
        JComponent editor_js7 = AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.getEditor();
        JFormattedTextField tf_js7 = ((JSpinner.DefaultEditor) editor_js7).getTextField();
        tf_js7.setEditable(false);
        tf_js7.setColumns(3);
        tf_js7.setHorizontalAlignment(JTextField.CENTER);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setSize(64, 32);

        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setFocusable(false);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setRequestFocusEnabled(false);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Phut_JSpinner);
        JComponent editor_js8 = AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.getEditor();
        JFormattedTextField tf_js8 = ((JSpinner.DefaultEditor) editor_js8).getTextField();
        tf_js8.setEditable(false);
        tf_js8.setColumns(3);
        tf_js8.setHorizontalAlignment(JTextField.CENTER);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setSize(64, 32);

        AMF_AM_PM_JComboBox.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_AM_PM_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        AMF_AM_PM_JComboBox.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_AM_PM_JComboBox.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_AM_PM_JComboBox.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_AM_PM_JComboBox);

        AMF_LieuSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_LieuSuDung_JLabel.setText("Liều sử dụng");
        AMF_LieuSuDung_JLabel.setMaximumSize(new java.awt.Dimension(140, 30));
        AMF_LieuSuDung_JLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        AMF_LieuSuDung_JLabel.setPreferredSize(new java.awt.Dimension(180, 30));
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_LieuSuDung_JLabel);

        AMF_LieuSuDung_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_LieuSuDung_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_LieuSuDung_JSpinner.setFocusable(false);
        AMF_LieuSuDung_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setRequestFocusEnabled(false);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_LieuSuDung_JSpinner);
        JComponent editor_js9 = AMF_LieuSuDung_JSpinner.getEditor();
        JFormattedTextField tf_js9 = ((JSpinner.DefaultEditor) editor_js9).getTextField();
        tf_js9.setEditable(false);
        tf_js9.setColumns(3);
        tf_js9.setHorizontalAlignment(JTextField.CENTER);
        AMF_LieuSuDung_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_JPanel);

        AMF_NoiDungThemThuoc_JScrollPane.setViewportView(AMF_KhungNoiDungThemThuoc_JPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AMF_ThanhChucNang_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(AMF_NoiDungThemThuoc_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AMF_ThanhChucNang_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AMF_NoiDungThemThuoc_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AMF_Huy_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Huy_JButtonActionPerformed
        this.mf.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_AMF_Huy_JButtonActionPerformed

    private void AMF_Them_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Them_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_Them_JButtonActionPerformed

    private void AMF_Ten_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Ten_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_Ten_JTextFieldActionPerformed

    private void AMF_UuTienThongBao_JToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_UuTienThongBao_JToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_UuTienThongBao_JToggleButtonActionPerformed

    private void AMF_TanSuatSuDung_JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_TanSuatSuDung_JComboBoxActionPerformed
        // TODO add your handling code here:
        if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Mỗi ngày")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tuần")) {
            AMF_TanSuatSuDung_JButton.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tháng")) {
            AMF_TanSuatSuDung_JButton.setEnabled(true);
        } else {
            AMF_TanSuatSuDung_JButton.setEnabled(true);
        }
    }//GEN-LAST:event_AMF_TanSuatSuDung_JComboBoxActionPerformed

    private void AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed

    private void AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked
      	TimeStoneAdditionPanel JP = new TimeStoneAdditionPanel(AMF_KhungNoiDungThemThuoc_JPanel);
		JP.setSize(AMF_MocThoiGianSuDungThuoc_JPanel.getSize());
        
        LayoutManager layout = AMF_KhungNoiDungThemThuoc_JPanel.getLayout();
        
        if (layout instanceof GridLayout) {
            ((GridLayout) layout).setColumns(1);
            ((GridLayout) layout).setRows(((GridLayout) layout).getRows() + 1);
            AMF_KhungNoiDungThemThuoc_JPanel.setLayout(layout);
            AMF_KhungNoiDungThemThuoc_JPanel.add(JP, -1);
            AMF_KhungNoiDungThemThuoc_JPanel.revalidate();
            AMF_KhungNoiDungThemThuoc_JPanel.repaint();
        }
        
    }//GEN-LAST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked

    private void AMF_TanSuatSuDung_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_TanSuatSuDung_JButtonActionPerformed
        // TODO add your handling code here:
		var data= "";
        if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Mỗi ngày")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false); 
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tuần")) {
            data = JOptionPane.showInputDialog(this, "Nhập các ngày trong tuần bạn muốn\n(phân cách bằng dấu \",\"):\n" + "2: Thứ Hai, 3: Thứ Ba, 4: Thứ Tư\n5: Thứ Năm, 6: Thứ Sáu, 7: Thứ Bảy\n8: Chủ Nhật", "Lựa chọn ngày trong tuần", JOptionPane.QUESTION_MESSAGE);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tháng")) {
            data = JOptionPane.showInputDialog(this, "Nhập các ngày trong tháng bạn muốn\n(phân cách bằng dấu \",\"): ", "Lựa chọn ngày trong tháng", JOptionPane.QUESTION_MESSAGE);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Khi cần thiết")) {
			AMF_TanSuatSuDung_JButton.setEnabled(false); 
        }
    }//GEN-LAST:event_AMF_TanSuatSuDung_JButtonActionPerformed

    private void AMF_TanSuatSuDung_JComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AMF_TanSuatSuDung_JComboBoxItemStateChanged
        // TODO add your handling code here:
		AMF_TanSuatSuDung_JButton.setEnabled(false);
		var data= "";
        if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Mỗi ngày")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false); 
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tuần")) {
			AMF_TanSuatSuDung_JButton.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tháng")) {
			AMF_TanSuatSuDung_JButton.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Khi cần thiết")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false);
			AMF_UuTienThongBao_JToggleButton.setEnabled(false);
			AMF_TuDongXacNhanSuDung_JToggleButton.setEnabled(false);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_AMF_TanSuatSuDung_JComboBoxItemStateChanged

    private void AMF_MocThoiGianSuDungThuoc_Them_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonActionPerformed
//        // TODO add your handling code here:
//		LayoutManager layout = AMF_KhungNoiDungThemThuoc_JPanel.getLayout();
//		JPanel jp = AMF_MocThoiGianSuDungThuoc_JPanel;
//		if (layout instanceof GridLayout) {
//            ((GridLayout) layout).setColumns(1);
//            ((GridLayout) layout).setRows(((GridLayout) layout).getRows() + 1);
//            AMF_KhungNoiDungThemThuoc_JPanel.setLayout(layout);
//            AMF_KhungNoiDungThemThuoc_JPanel.add(jp, -1);
//            AMF_KhungNoiDungThemThuoc_JPanel.revalidate();
//            AMF_KhungNoiDungThemThuoc_JPanel.repaint();
//        }
    }//GEN-LAST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicationFrame(mf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AMF_AM_PM_JComboBox;
    private javax.swing.JLabel AMF_DonVi_JLabel;
    private javax.swing.JPanel AMF_DonVi_JPanel;
    private javax.swing.JTextField AMF_DonVi_JTextField;
    private javax.swing.JLabel AMF_GhiChu_JLabel;
    private javax.swing.JPanel AMF_GhiChu_JPanel;
    private javax.swing.JTextField AMF_GhiChu_JTextField;
    private javax.swing.JLabel AMF_HienCo_JLabel;
    private javax.swing.JSpinner AMF_HienCo_JSpinner;
    private javax.swing.JButton AMF_Huy_JButton;
    private javax.swing.JLabel AMF_KhoangThoiGianLapThongBao_JLabel;
    private javax.swing.JPanel AMF_KhoangThoiGianLapThongBao_JPanel;
    private javax.swing.JSpinner AMF_KhoangThoiGianLapThongBao_JSpinner;
    private javax.swing.JPanel AMF_KhungNoiDungThemThuoc_JPanel;
    private javax.swing.JLabel AMF_LieuSuDung_JLabel;
    private javax.swing.JSpinner AMF_LieuSuDung_JSpinner;
    private javax.swing.JSpinner AMF_MocThoiGianSuDungThuoc_Gio_JSpinner;
    private javax.swing.JPanel AMF_MocThoiGianSuDungThuoc_JPanel;
    private javax.swing.JSpinner AMF_MocThoiGianSuDungThuoc_Phut_JSpinner;
    private javax.swing.JButton AMF_MocThoiGianSuDungThuoc_Them_JButton;
    private javax.swing.JLabel AMF_NhacNho_JLabel;
    private javax.swing.JSpinner AMF_NhacNho_JSpinner;
    private javax.swing.JScrollPane AMF_NoiDungThemThuoc_JScrollPane;
    private javax.swing.JLabel AMF_QuanLySoLuongThuoc_JLabel;
    private javax.swing.JPanel AMF_QuanLySoLuongThuoc_JPanel;
    private javax.swing.JButton AMF_TanSuatSuDung_JButton;
    private javax.swing.JComboBox<String> AMF_TanSuatSuDung_JComboBox;
    private javax.swing.JLabel AMF_TanSuatSuDung_JLabel;
    private javax.swing.JPanel AMF_TanSuatSuDung_JPanel;
    private javax.swing.JLabel AMF_Ten_JLabel;
    private javax.swing.JPanel AMF_Ten_JPanel;
    private javax.swing.JTextField AMF_Ten_JTextField;
    private javax.swing.JPanel AMF_ThanhChucNang_JPanel;
    private javax.swing.JLabel AMF_ThemDonThuocMoi_JLabel;
    private javax.swing.JButton AMF_Them_JButton;
    private javax.swing.JLabel AMF_TuDongXacNhanSuDung_JLabel;
    private javax.swing.JPanel AMF_TuDongXacNhanSuDung_JPanel;
    private javax.swing.JToggleButton AMF_TuDongXacNhanSuDung_JToggleButton;
    private javax.swing.JLabel AMF_UuTienThongBao_JLabel;
    private javax.swing.JPanel AMF_UuTienThongBao_JPanel;
    private javax.swing.JToggleButton AMF_UuTienThongBao_JToggleButton;
    // End of variables declaration//GEN-END:variables
}
