/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import java.sql.*;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import supervisorview.*;
import object.EmailUtil;
/**
 *
 * @author shanghuang
 */
public class AuthenticationFrame extends javax.swing.JFrame {
    int DEBUG = 1;
	public String charset = "<>?/.,:\";'{}|\\[\\]\\\\()!@#$%^&*\\-_+=~`";
	Pattern patt = Pattern.compile("[" + charset + "]");
	private String Username = null;
    /**
     * Creates new form AuthenticationFrame
     */
    public AuthenticationFrame() {
		FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
        initComponents();
		AF_MatKhau_JTF_JL_JPanel.putClientProperty(FlatClientProperties.STYLE, "arc: 10" );
		AF_QuenMatKhau_JL_JB_JPanel.putClientProperty(FlatClientProperties.STYLE, "arc: 10" );
		AF_TenDangNhap_JTF_JL_JPanel.putClientProperty(FlatClientProperties.STYLE, "arc: 10" );
		AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel.putClientProperty(FlatClientProperties.STYLE, "arc: 10" );
        this.setVisible(true);
        this.setFrameInCenter();
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AF_Title_JLabel = new javax.swing.JLabel();
        AF_Subtitle_JLabel = new javax.swing.JLabel();
        AF_TenDangNhap_JTF_JL_JPanel = new javax.swing.JPanel();
        AF_TenDangNhap_JLabel = new javax.swing.JLabel();
        AF_TenDangNhap_JTextField = new javax.swing.JTextField();
        AF_MatKhau_JTF_JL_JPanel = new javax.swing.JPanel();
        AF_MatKhau_JLabel = new javax.swing.JLabel();
        AF_MatKhau_JPasswordField = new javax.swing.JPasswordField();
        AF_QuenMatKhau_JL_JB_JPanel = new javax.swing.JPanel();
        AF_QuenMatKhau_JLabel = new javax.swing.JLabel();
        AF_QuenMatKhau_JButton = new javax.swing.JButton();
        AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel = new javax.swing.JPanel();
        AF_KhongTaiKhoan_JLabel = new javax.swing.JLabel();
        AF_KhongTaiKhoan_JButton = new javax.swing.JButton();
        AF_DangNhap_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        AF_Title_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 1, 36)); // NOI18N
        AF_Title_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AF_Title_JLabel.setText("ỨNG DỤNG QUẢN LÝ DƯỢC PHẨM CÁ NHÂN");

        AF_Subtitle_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        AF_Subtitle_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AF_Subtitle_JLabel.setText("Đăng nhập tài khoản");

        AF_TenDangNhap_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        AF_TenDangNhap_JLabel.setText("Tên đăng nhập:");
        AF_TenDangNhap_JTF_JL_JPanel.add(AF_TenDangNhap_JLabel);

        AF_TenDangNhap_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        AF_TenDangNhap_JTextField.setPreferredSize(new java.awt.Dimension(300, 43));
        AF_TenDangNhap_JTF_JL_JPanel.add(AF_TenDangNhap_JTextField);

        AF_MatKhau_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        AF_MatKhau_JLabel.setText("Mật khẩu:");
        AF_MatKhau_JLabel.setPreferredSize(new java.awt.Dimension(266, 37));
        AF_MatKhau_JTF_JL_JPanel.add(AF_MatKhau_JLabel);

        AF_MatKhau_JPasswordField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        AF_MatKhau_JPasswordField.setPreferredSize(new java.awt.Dimension(300, 43));
        AF_MatKhau_JTF_JL_JPanel.add(AF_MatKhau_JPasswordField);

        AF_QuenMatKhau_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AF_QuenMatKhau_JLabel.setText("Quên mật khẩu");
        AF_QuenMatKhau_JLabel.setToolTipText("");
        AF_QuenMatKhau_JLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        AF_QuenMatKhau_JL_JB_JPanel.add(AF_QuenMatKhau_JLabel);

        AF_QuenMatKhau_JButton.setText("Nhấn vào đây");
        AF_QuenMatKhau_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AF_QuenMatKhau_JButtonActionPerformed(evt);
            }
        });
        AF_QuenMatKhau_JL_JB_JPanel.add(AF_QuenMatKhau_JButton);

        AF_KhongTaiKhoan_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AF_KhongTaiKhoan_JLabel.setText("Chưa có tài khoản?");
        AF_KhongTaiKhoan_JLabel.setToolTipText("");
        AF_KhongTaiKhoan_JLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel.add(AF_KhongTaiKhoan_JLabel);

        AF_KhongTaiKhoan_JButton.setText("Nhấn vào đây");
        AF_KhongTaiKhoan_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AF_KhongTaiKhoan_JButtonActionPerformed(evt);
            }
        });
        AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel.add(AF_KhongTaiKhoan_JButton);

        AF_DangNhap_JButton.setText("ĐĂNG NHẬP");
        AF_DangNhap_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AF_DangNhap_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AF_Title_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AF_Subtitle_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AF_TenDangNhap_JTF_JL_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AF_MatKhau_JTF_JL_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AF_DangNhap_JButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AF_QuenMatKhau_JL_JB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AF_Title_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AF_Subtitle_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(AF_TenDangNhap_JTF_JL_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AF_MatKhau_JTF_JL_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(AF_QuenMatKhau_JL_JB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AF_DangNhap_JButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // connector for jdbc
    private Connection connect() {
        // connection parameter
        String dbURL = "jdbc:oracle:thin:@192.168.124.180:32772:XE";
        String driver = "oracle.jdbc.OracleDriver";
        Connection con = null;
        
        // catching error in connection
        try {
            // class loader
            Class.forName(driver);
            
            // connection
            con = DriverManager.getConnection(dbURL, "c##shanghuang", "181105");

            // debug block
            if (con != null) {
                if (DEBUG == 1) {
                    System.out.println("Kết nối đến cơ sử dữ liệu thành công");
                }
            }
        } catch(SQLException se) { 
            // sql exception
            System.out.println(se.getMessage());
        } catch (ClassNotFoundException ex) { 
            // class exception
            Logger.getLogger(AuthenticationFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Return connection
        if (con != null) {
            return con;
        } else {
            return null;
        }
    }
    
	public boolean checkIllegalCharacter(String inp, Pattern pat) {
		Matcher match = pat.matcher(inp);
		return match.find();
	}
	
    private void AF_DangNhap_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AF_DangNhap_JButtonActionPerformed
        // TODO add your handling code here:
        String TenDangNhapVariableHolder = AF_TenDangNhap_JTextField.getText();
        String MatKhauVariableHolder = new String(AF_MatKhau_JPasswordField.getPassword());
        
        if (
            TenDangNhapVariableHolder.equals("") ||
            MatKhauVariableHolder.equals("")
        ) {
            JOptionPane.showMessageDialog(this, "Thông tin đăng nhập không được bỏ trống");
        } else {
            if (checkIllegalCharacter(TenDangNhapVariableHolder, patt)) {
				JOptionPane.showMessageDialog(this, "Username không được phép tồn tại ký tự đặc biệt. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
			} else {
				// Create connection
				Connection con = connect();

				if (con == null) {
					// debug block
					if (DEBUG == 1) {
					System.out.println("Không thể kết nối đến cơ sử dữ liệu");
					}
				} else {
					// query parameter
					boolean result = false;
					ResultSet rs = null;
					String query = "SELECT CANHAN.USERNAME FROM CANHAN WHERE CANHAN.USERNAME = ? AND CANHAN.MATKHAU = ?";

					// catching error in query execution
					try {
						// load parameter in to query
						PreparedStatement ps = con.prepareStatement(query);
						ps.setString(1, TenDangNhapVariableHolder);
						ps.setString(2, MatKhauVariableHolder);

						// execute and return boolean value to confirm connection
						rs = ps.executeQuery();
						if (rs.next()) {
							result = true;
						} else {
							result = false;
						}
						con.close();
					} catch (SQLException se) {
						// SQL Exception
						System.out.println(se.getMessage());
					}

					// checking connection confirm
					if (result == false) {
						// error display
						JOptionPane.showMessageDialog(this, "Đăng nhập không thành công. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);

						// debug block
						if (DEBUG == 1) {
							System.out.println("No user found");
						}
					} else {
						// success display
						JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Success", JOptionPane.INFORMATION_MESSAGE);
						this.Username = TenDangNhapVariableHolder;
						
						MainFrame mf = new MainFrame(this.Username);
						this.dispose();

						// debug block
						if (DEBUG == 1) {
							System.out.println("User found");
						}
					}
				}
			}
        }
    }//GEN-LAST:event_AF_DangNhap_JButtonActionPerformed

    private void AF_KhongTaiKhoan_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AF_KhongTaiKhoan_JButtonActionPerformed
        // TODO add your handling code here:
        CreateAccountFrame CAF = new CreateAccountFrame(AuthenticationFrame.this);
        this.dispose();
    }//GEN-LAST:event_AF_KhongTaiKhoan_JButtonActionPerformed

    private void AF_QuenMatKhau_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AF_QuenMatKhau_JButtonActionPerformed
        // TODO add your handling code here:
        ForgotPasswordFrame FPF = new ForgotPasswordFrame(AuthenticationFrame.this);
        this.dispose();
    }//GEN-LAST:event_AF_QuenMatKhau_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AF_DangNhap_JButton;
    private javax.swing.JPanel AF_KhongTaiKhoan_DangNhap_JL_JB_JPanel;
    private javax.swing.JButton AF_KhongTaiKhoan_JButton;
    private javax.swing.JLabel AF_KhongTaiKhoan_JLabel;
    private javax.swing.JLabel AF_MatKhau_JLabel;
    private javax.swing.JPasswordField AF_MatKhau_JPasswordField;
    private javax.swing.JPanel AF_MatKhau_JTF_JL_JPanel;
    private javax.swing.JButton AF_QuenMatKhau_JButton;
    private javax.swing.JPanel AF_QuenMatKhau_JL_JB_JPanel;
    private javax.swing.JLabel AF_QuenMatKhau_JLabel;
    private javax.swing.JLabel AF_Subtitle_JLabel;
    private javax.swing.JLabel AF_TenDangNhap_JLabel;
    private javax.swing.JPanel AF_TenDangNhap_JTF_JL_JPanel;
    private javax.swing.JTextField AF_TenDangNhap_JTextField;
    private javax.swing.JLabel AF_Title_JLabel;
    // End of variables declaration//GEN-END:variables
}
