/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.UIManager;
import object.MedicineObject;

/**
 *
 * @author shanghuang
 */
public class InstantUseFrame extends javax.swing.JFrame {
	public static MainFrame mf;
	public static String UserName = null;

	/**
	 * Creates new form InstantUseFrame
	 */
	public InstantUseFrame(MainFrame mf, String UserName) {
		this.UserName = UserName;
		this.mf = mf;
		FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
		initComponents();
		this.setVisible(true);
		loadData();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IUF_Intermidiate_JPanel = new javax.swing.JPanel();
        IUF_Title_JLabel = new javax.swing.JLabel();
        IUF_Divider_JSeperator = new javax.swing.JSeparator();
        IUF_TenThuoc_JPanel = new javax.swing.JPanel();
        IUF_TenThuoc_JLabel = new javax.swing.JLabel();
        IUF_TenThuoc_JComboBox = new javax.swing.JComboBox<>();
        IUF_GhiChu_JPanel = new javax.swing.JPanel();
        IUF_GhiChu_JLabel = new javax.swing.JLabel();
        IUF_GhiChu_JTextField = new javax.swing.JTextField();
        IUF_LieuSuDung_JPanel = new javax.swing.JPanel();
        IUF_LieuSuDung_JLabel = new javax.swing.JLabel();
        IUF_LieuSuDung_JTextField = new javax.swing.JTextField();
        IUF_ThoiGian_JPanel = new javax.swing.JPanel();
        IUF_ThoiGian_JLabel = new javax.swing.JLabel();
        IUF_ThoiGian_JTextField = new javax.swing.JTextField();
        IUF_NgaySuDung_JPanel = new javax.swing.JPanel();
        IUF_NgaySuDung_JLabel = new javax.swing.JLabel();
        IUF_NgaySuDung_JTextField = new javax.swing.JTextField();
        IUF_ThanhChucNang_JPanel = new javax.swing.JPanel();
        IUF_TroVe_JButton = new javax.swing.JButton();
        IUF_XacNhan_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1, 5, 5));

        IUF_Intermidiate_JPanel.setMaximumSize(new java.awt.Dimension(488, 288));
        IUF_Intermidiate_JPanel.setMinimumSize(new java.awt.Dimension(488, 288));
        IUF_Intermidiate_JPanel.setLayout(new java.awt.GridLayout(8, 1, 5, 5));

        IUF_Title_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        IUF_Title_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IUF_Title_JLabel.setText("Sử dụng tức thì");
        IUF_Title_JLabel.setMaximumSize(new java.awt.Dimension(200, 30));
        IUF_Title_JLabel.setMinimumSize(new java.awt.Dimension(200, 30));
        IUF_Title_JLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        IUF_Intermidiate_JPanel.add(IUF_Title_JLabel);
        IUF_Intermidiate_JPanel.add(IUF_Divider_JSeperator);

        IUF_TenThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IUF_TenThuoc_JLabel.setText("Tên thuốc");
        IUF_TenThuoc_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_TenThuoc_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_TenThuoc_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_TenThuoc_JPanel.add(IUF_TenThuoc_JLabel);

        IUF_TenThuoc_JComboBox.setMaximumSize(new java.awt.Dimension(300, 30));
        IUF_TenThuoc_JComboBox.setMinimumSize(new java.awt.Dimension(300, 30));
        IUF_TenThuoc_JComboBox.setPreferredSize(new java.awt.Dimension(300, 30));
        IUF_TenThuoc_JComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUF_TenThuoc_JComboBoxActionPerformed(evt);
            }
        });
        IUF_TenThuoc_JPanel.add(IUF_TenThuoc_JComboBox);

        IUF_Intermidiate_JPanel.add(IUF_TenThuoc_JPanel);

        IUF_GhiChu_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IUF_GhiChu_JLabel.setText("Ghi chú");
        IUF_GhiChu_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_GhiChu_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_GhiChu_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_GhiChu_JPanel.add(IUF_GhiChu_JLabel);

        IUF_GhiChu_JTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        IUF_GhiChu_JTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        IUF_GhiChu_JTextField.setPreferredSize(new java.awt.Dimension(300, 30));
        IUF_GhiChu_JPanel.add(IUF_GhiChu_JTextField);

        IUF_Intermidiate_JPanel.add(IUF_GhiChu_JPanel);

        IUF_LieuSuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IUF_LieuSuDung_JLabel.setText("Liều sử dụng");
        IUF_LieuSuDung_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_LieuSuDung_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_LieuSuDung_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_LieuSuDung_JPanel.add(IUF_LieuSuDung_JLabel);

        IUF_LieuSuDung_JTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        IUF_LieuSuDung_JTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        IUF_LieuSuDung_JTextField.setPreferredSize(new java.awt.Dimension(300, 30));
        IUF_LieuSuDung_JPanel.add(IUF_LieuSuDung_JTextField);

        IUF_Intermidiate_JPanel.add(IUF_LieuSuDung_JPanel);

        IUF_ThoiGian_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IUF_ThoiGian_JLabel.setText("Thời gian");
        IUF_ThoiGian_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_ThoiGian_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_ThoiGian_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_ThoiGian_JPanel.add(IUF_ThoiGian_JLabel);

        IUF_ThoiGian_JTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        IUF_ThoiGian_JTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        IUF_ThoiGian_JTextField.setPreferredSize(new java.awt.Dimension(300, 30));
        IUF_ThoiGian_JPanel.add(IUF_ThoiGian_JTextField);

        IUF_Intermidiate_JPanel.add(IUF_ThoiGian_JPanel);

        IUF_NgaySuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        IUF_NgaySuDung_JLabel.setText("Ngày sử dụng");
        IUF_NgaySuDung_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_NgaySuDung_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_NgaySuDung_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_NgaySuDung_JPanel.add(IUF_NgaySuDung_JLabel);

        IUF_NgaySuDung_JTextField.setMaximumSize(new java.awt.Dimension(300, 30));
        IUF_NgaySuDung_JTextField.setMinimumSize(new java.awt.Dimension(300, 30));
        IUF_NgaySuDung_JTextField.setPreferredSize(new java.awt.Dimension(300, 30));
        IUF_NgaySuDung_JPanel.add(IUF_NgaySuDung_JTextField);

        IUF_Intermidiate_JPanel.add(IUF_NgaySuDung_JPanel);

        IUF_TroVe_JButton.setText("Trở về");
        IUF_TroVe_JButton.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_TroVe_JButton.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_TroVe_JButton.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_TroVe_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUF_TroVe_JButtonActionPerformed(evt);
            }
        });
        IUF_ThanhChucNang_JPanel.add(IUF_TroVe_JButton);

        IUF_XacNhan_JButton.setText("Xác nhận");
        IUF_XacNhan_JButton.setMaximumSize(new java.awt.Dimension(150, 30));
        IUF_XacNhan_JButton.setMinimumSize(new java.awt.Dimension(150, 30));
        IUF_XacNhan_JButton.setPreferredSize(new java.awt.Dimension(150, 30));
        IUF_XacNhan_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IUF_XacNhan_JButtonActionPerformed(evt);
            }
        });
        IUF_ThanhChucNang_JPanel.add(IUF_XacNhan_JButton);

        IUF_Intermidiate_JPanel.add(IUF_ThanhChucNang_JPanel);

        getContentPane().add(IUF_Intermidiate_JPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IUF_TroVe_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IUF_TroVe_JButtonActionPerformed
        this.mf.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_IUF_TroVe_JButtonActionPerformed

    private void IUF_XacNhan_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IUF_XacNhan_JButtonActionPerformed
        this.mf.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_IUF_XacNhan_JButtonActionPerformed

	private void loadData() {
		String UserNameFolder = "/home/shanghuang/SMM_STO_" + this.UserName;
		String MedicineFilePath = UserNameFolder + "/MO";
		List<String> l = new ArrayList<>();
		
		File folder = new File(MedicineFilePath);
		
		// goto the folder and add med name into l
		if (folder.exists() && folder.isDirectory()) {
			File[] lof = folder.listFiles();
			
			if (lof != null) {
				for (File file : lof) {
					if (file.isFile() && file.getName().toLowerCase().endsWith(".json")) {
						String fileName = file.getName();
						String medicineName = fileName.substring(3, fileName.length() - 5);
						l.add(medicineName.trim());
					}
				}
			}
		} else {
			System.err.println("Thư mục không tồn tại hoặc không phải là thư mục: " + MedicineFilePath);
		}
		
		// In ra danh sách tên thuốc (hoặc xử lý theo nhu cầu của bạn)
		System.out.println("Danh sách tên thuốc: " + l);
		
		Collections.sort(l); 
		
		IUF_TenThuoc_JComboBox.removeAllItems();
		for (Object o : l) {
			IUF_TenThuoc_JComboBox.addItem(o.toString());
		}

        // set date and time value to IUF_NgaySuDung_JTextField and IUF_ThoiGian_JTextField
        Date now = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        IUF_NgaySuDung_JTextField.setText(dateFormat.format(now));
        IUF_ThoiGian_JTextField.setText(timeFormat.format(now));
	}
	
    private void IUF_TenThuoc_JComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IUF_TenThuoc_JComboBoxActionPerformed
		String TenThuoc = IUF_TenThuoc_JComboBox.getSelectedItem().toString();
		String UserNameFolder = "/home/shanghuang/SMM_STO_" + this.UserName;
		String MedicineFilePath = UserNameFolder + "/MO/MO_" + TenThuoc + ".json";
		
		MedicineObject mo = new MedicineObject();
		
		mo.readJSON(MedicineFilePath);
		
		IUF_GhiChu_JTextField.setText(mo.getDonVi());
		
    }//GEN-LAST:event_IUF_TenThuoc_JComboBoxActionPerformed

	
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InstantUseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InstantUseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InstantUseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InstantUseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InstantUseFrame(mf, UserName).setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator IUF_Divider_JSeperator;
    private javax.swing.JLabel IUF_GhiChu_JLabel;
    private javax.swing.JPanel IUF_GhiChu_JPanel;
    private javax.swing.JTextField IUF_GhiChu_JTextField;
    private javax.swing.JPanel IUF_Intermidiate_JPanel;
    private javax.swing.JLabel IUF_LieuSuDung_JLabel;
    private javax.swing.JPanel IUF_LieuSuDung_JPanel;
    private javax.swing.JTextField IUF_LieuSuDung_JTextField;
    private javax.swing.JLabel IUF_NgaySuDung_JLabel;
    private javax.swing.JPanel IUF_NgaySuDung_JPanel;
    private javax.swing.JTextField IUF_NgaySuDung_JTextField;
    private javax.swing.JComboBox<String> IUF_TenThuoc_JComboBox;
    private javax.swing.JLabel IUF_TenThuoc_JLabel;
    private javax.swing.JPanel IUF_TenThuoc_JPanel;
    private javax.swing.JPanel IUF_ThanhChucNang_JPanel;
    private javax.swing.JLabel IUF_ThoiGian_JLabel;
    private javax.swing.JPanel IUF_ThoiGian_JPanel;
    private javax.swing.JTextField IUF_ThoiGian_JTextField;
    private javax.swing.JLabel IUF_Title_JLabel;
    private javax.swing.JButton IUF_TroVe_JButton;
    private javax.swing.JButton IUF_XacNhan_JButton;
    // End of variables declaration//GEN-END:variables
}
