/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userview;

/**
 *
 * @author shanghuang
 */
public class MedicineItemPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MedicineItemPanel
	 */
	public MedicineItemPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1041, 90));
        setMinimumSize(new java.awt.Dimension(1041, 90));
        setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabel1.setFont(new java.awt.Font("SF Mono SemiBold", 0, 24)); // NOI18N
        jLabel1.setText("TenThuoc");
        jLabel1.setMaximumSize(new java.awt.Dimension(1029, 54));
        jLabel1.setMinimumSize(new java.awt.Dimension(1029, 54));
        jLabel1.setPreferredSize(new java.awt.Dimension(1029, 54));
        add(jLabel1);

        jPanel3.setMaximumSize(new java.awt.Dimension(1029, 54));
        jPanel3.setMinimumSize(new java.awt.Dimension(1029, 54));
        jPanel3.setPreferredSize(new java.awt.Dimension(1029, 54));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        jLabel2.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        jLabel2.setText("DonViThuoc");
        jLabel2.setMaximumSize(new java.awt.Dimension(150, 30));
        jLabel2.setMinimumSize(new java.awt.Dimension(150, 30));
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("GhiChuThuoc");
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 30));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("UuTien");
        jLabel4.setMaximumSize(new java.awt.Dimension(180, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(180, 30));
        jLabel4.setPreferredSize(new java.awt.Dimension(180, 30));
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        jLabel5.setText("SL");
        jLabel5.setMaximumSize(new java.awt.Dimension(90, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(90, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(90, 30));
        jPanel1.add(jLabel5);

        jPanel3.add(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(186, 42));
        jPanel2.setMinimumSize(new java.awt.Dimension(186, 42));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jPanel2.add(jButton1);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/duplicate.png"))); // NOI18N
        jPanel2.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jPanel2.add(jButton4);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refill.png"))); // NOI18N
        jPanel2.add(jButton2);

        jPanel3.add(jPanel2);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
