/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Hinno
 */
public class AccountInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountFrame
     */
    public AccountInformationFrame() {
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
        this.setFrameInCenter();
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AIF_IntermidiateContainer_JPanel = new javax.swing.JPanel();
        AIF_TaoTaiKhoan_JLabel = new javax.swing.JLabel();
        AIF_TenTaiKhoan_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_TenTaiKhoan_JLabel = new javax.swing.JLabel();
        CAF_TenTaiKhoan_JTextField = new javax.swing.JTextField();
        AIF_HoTen_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_HoTen_JLabel = new javax.swing.JLabel();
        CAF_HoTen_JTextField = new javax.swing.JTextField();
        AIF_Email_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_Email_JLabel = new javax.swing.JLabel();
        CAF_Email_JTextField = new javax.swing.JTextField();
        AIF_Tuoi_JL_JS_JPanel = new javax.swing.JPanel();
        CAF_Tuoi_JLabel = new javax.swing.JLabel();
        CAF_Tuoi_JSpinner = new javax.swing.JSpinner();
        AIF_KhuVucSinhSong_JL_JCB_JPanel = new javax.swing.JPanel();
        CAF_KhuVucSinhSong_JLabel = new javax.swing.JLabel();
        CAF_KhuVucSinhSong_JComboBox = new javax.swing.JComboBox<>();
        AIF_TienSuBenhLy_JL_JTA_JPanel = new javax.swing.JPanel();
        CAF_TienSuBenhLy_JLabel = new javax.swing.JLabel();
        CAF_TienSuBenhLy_JTextArea = new javax.swing.JTextArea();
        AIF_XacNhan_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        AIF_TaoTaiKhoan_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 36)); // NOI18N
        AIF_TaoTaiKhoan_JLabel.setText("TÀI KHOẢN");

        AIF_TenTaiKhoan_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_TenTaiKhoan_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_TenTaiKhoan_JLabel.setText("Tên tài khoản:");
        AIF_TenTaiKhoan_JL_JTF_JPanel.add(CAF_TenTaiKhoan_JLabel);

        CAF_TenTaiKhoan_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_TenTaiKhoan_JTextField.setPreferredSize(new java.awt.Dimension(420, 30));
        AIF_TenTaiKhoan_JL_JTF_JPanel.add(CAF_TenTaiKhoan_JTextField);

        AIF_HoTen_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_HoTen_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_HoTen_JLabel.setText("Họ tên:");
        AIF_HoTen_JL_JTF_JPanel.add(CAF_HoTen_JLabel);

        CAF_HoTen_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_HoTen_JTextField.setPreferredSize(new java.awt.Dimension(525, 30));
        AIF_HoTen_JL_JTF_JPanel.add(CAF_HoTen_JTextField);

        AIF_Email_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_Email_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_Email_JLabel.setText("Email:");
        AIF_Email_JL_JTF_JPanel.add(CAF_Email_JLabel);

        CAF_Email_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_Email_JTextField.setPreferredSize(new java.awt.Dimension(540, 30));
        AIF_Email_JL_JTF_JPanel.add(CAF_Email_JTextField);

        AIF_Tuoi_JL_JS_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_Tuoi_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_Tuoi_JLabel.setText("Tuổi:");
        AIF_Tuoi_JL_JS_JPanel.add(CAF_Tuoi_JLabel);

        CAF_Tuoi_JSpinner.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        CAF_Tuoi_JSpinner.setPreferredSize(new java.awt.Dimension(82, 30));
        AIF_Tuoi_JL_JS_JPanel.add(CAF_Tuoi_JSpinner);

        AIF_KhuVucSinhSong_JL_JCB_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_KhuVucSinhSong_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_KhuVucSinhSong_JLabel.setText("Khu vực sinh sống:");
        AIF_KhuVucSinhSong_JL_JCB_JPanel.add(CAF_KhuVucSinhSong_JLabel);

        CAF_KhuVucSinhSong_JComboBox.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        CAF_KhuVucSinhSong_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miền Bắc", "Miền Trung", "Miền Nam", " " }));
        CAF_KhuVucSinhSong_JComboBox.setPreferredSize(new java.awt.Dimension(170, 30));
        AIF_KhuVucSinhSong_JL_JCB_JPanel.add(CAF_KhuVucSinhSong_JComboBox);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        AIF_TienSuBenhLy_JL_JTA_JPanel.setLayout(flowLayout1);

        CAF_TienSuBenhLy_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_TienSuBenhLy_JLabel.setText("Tiền sử bệnh lý:");
        AIF_TienSuBenhLy_JL_JTA_JPanel.add(CAF_TienSuBenhLy_JLabel);

        CAF_TienSuBenhLy_JTextArea.setColumns(20);
        CAF_TienSuBenhLy_JTextArea.setRows(5);
        CAF_TienSuBenhLy_JTextArea.setPreferredSize(new java.awt.Dimension(385, 100));
        AIF_TienSuBenhLy_JL_JTA_JPanel.add(CAF_TienSuBenhLy_JTextArea);

        AIF_XacNhan_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        AIF_XacNhan_JButton.setText("OK");
        AIF_XacNhan_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AIF_XacNhan_JButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AIF_IntermidiateContainer_JPanelLayout = new javax.swing.GroupLayout(AIF_IntermidiateContainer_JPanel);
        AIF_IntermidiateContainer_JPanel.setLayout(AIF_IntermidiateContainer_JPanelLayout);
        AIF_IntermidiateContainer_JPanelLayout.setHorizontalGroup(
            AIF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addGroup(AIF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AIF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                        .addGroup(AIF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AIF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AIF_TenTaiKhoan_JL_JTF_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AIF_HoTen_JL_JTF_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AIF_Tuoi_JL_JS_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AIF_KhuVucSinhSong_JL_JCB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AIF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                                    .addGap(568, 568, 568)
                                    .addComponent(AIF_XacNhan_JButton))
                                .addComponent(AIF_Email_JL_JTF_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(AIF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(AIF_TaoTaiKhoan_JLabel)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(AIF_TienSuBenhLy_JL_JTA_JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        AIF_IntermidiateContainer_JPanelLayout.setVerticalGroup(
            AIF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AIF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(AIF_TaoTaiKhoan_JLabel)
                .addGap(18, 18, 18)
                .addComponent(AIF_TenTaiKhoan_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AIF_HoTen_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AIF_Email_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AIF_Tuoi_JL_JS_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AIF_TienSuBenhLy_JL_JTA_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AIF_KhuVucSinhSong_JL_JCB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AIF_XacNhan_JButton)
                .addContainerGap())
        );

        getContentPane().add(AIF_IntermidiateContainer_JPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AIF_XacNhan_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AIF_XacNhan_JButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AuthenticationFrame AF = new AuthenticationFrame();
    }//GEN-LAST:event_AIF_XacNhan_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInformationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AIF_Email_JL_JTF_JPanel;
    private javax.swing.JPanel AIF_HoTen_JL_JTF_JPanel;
    private javax.swing.JPanel AIF_IntermidiateContainer_JPanel;
    private javax.swing.JPanel AIF_KhuVucSinhSong_JL_JCB_JPanel;
    private javax.swing.JLabel AIF_TaoTaiKhoan_JLabel;
    private javax.swing.JPanel AIF_TenTaiKhoan_JL_JTF_JPanel;
    private javax.swing.JPanel AIF_TienSuBenhLy_JL_JTA_JPanel;
    private javax.swing.JPanel AIF_Tuoi_JL_JS_JPanel;
    private javax.swing.JButton AIF_XacNhan_JButton;
    private javax.swing.JLabel CAF_Email_JLabel;
    private javax.swing.JTextField CAF_Email_JTextField;
    private javax.swing.JLabel CAF_HoTen_JLabel;
    private javax.swing.JTextField CAF_HoTen_JTextField;
    private javax.swing.JComboBox<String> CAF_KhuVucSinhSong_JComboBox;
    private javax.swing.JLabel CAF_KhuVucSinhSong_JLabel;
    private javax.swing.JLabel CAF_TenTaiKhoan_JLabel;
    private javax.swing.JTextField CAF_TenTaiKhoan_JTextField;
    private javax.swing.JLabel CAF_TienSuBenhLy_JLabel;
    private javax.swing.JTextArea CAF_TienSuBenhLy_JTextArea;
    private javax.swing.JLabel CAF_Tuoi_JLabel;
    private javax.swing.JSpinner CAF_Tuoi_JSpinner;
    // End of variables declaration//GEN-END:variables
}
