/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;
import elementpanel.TimeStoneAdditionPanel;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
import object.MedicineObject;

/**
 *
 * @author Tina
 */
public class AddMedicationFrame extends javax.swing.JFrame {
	public static MainFrame mf;
	public String charset = "<>?/.,:\";'{}|\\[\\]\\\\()!@#$%^&*\\-_+=~`";
	Pattern patt = Pattern.compile("[" + charset + "]");
	int DEBUG = 0;
	String Specific_data = "2";
	public static String UserName = null;
	
    /**
     * Creates new form AddingMedFrame
     */
    public AddMedicationFrame(MainFrame mf, String UserName) {
		this.mf = mf;
		this.UserName = UserName;
        FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
        initComponents();
		AMF_TanSuatSuDung_JButton.setEnabled(false);
		AMF_ThanhChucNang_JPanel.putClientProperty(FlatClientProperties.STYLE, "arc: 10" );
		this.setFrameInCenter();
        this.setVisible(true);
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }
	
	public boolean checkUnit(String unit) {
		final Pattern UNIT_REGEX = Pattern.compile("^\\s*(\\d+(\\.\\d+)?)\\s*(viên|chiếc|tuýp|gói|lọ|vỉ|ống|chai|m[gG]|g|ml|cc)\\s*$", Pattern.CASE_INSENSITIVE);
		return UNIT_REGEX.matcher(unit).matches();
	}
	
	public boolean checkIllegalCharacter(String inp, Pattern pat) {
		Matcher match = pat.matcher(inp);
		return match.find();
	}
    
    public int get_JPanel2_height() {
        return this.AMF_MocThoiGianSuDungThuoc_JPanel.getSize().height;
    }
    
    public int get_JPanel10_height() {
        return this.AMF_KhungNoiDungThemThuoc_JPanel.getSize().height;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AMF_ThanhChucNang_JPanel = new javax.swing.JPanel();
        AMF_Huy_JButton = new javax.swing.JButton();
        AMF_ThemDonThuocMoi_JLabel = new javax.swing.JLabel();
        AMF_Them_JButton = new javax.swing.JButton();
        AMF_NoiDungThemThuoc_JScrollPane = new javax.swing.JScrollPane();
        AMF_KhungNoiDungThemThuoc_JPanel = new javax.swing.JPanel();
        AMF_Ten_JPanel = new javax.swing.JPanel();
        AMF_Ten_JLabel = new javax.swing.JLabel();
        AMF_Ten_JTextField = new javax.swing.JTextField();
        AMF_DonVi_JPanel = new javax.swing.JPanel();
        AMF_DonVi_JLabel = new javax.swing.JLabel();
        AMF_DonVi_JTextField = new javax.swing.JTextField();
        AMF_GhiChu_JPanel = new javax.swing.JPanel();
        AMF_GhiChu_JLabel = new javax.swing.JLabel();
        AMF_GhiChu_JTextField = new javax.swing.JTextField();
        AMF_TanSuatSuDung_JPanel = new javax.swing.JPanel();
        AMF_TanSuatSuDung_JLabel = new javax.swing.JLabel();
        AMF_TanSuatSuDung_JComboBox = new javax.swing.JComboBox<>();
        AMF_TanSuatSuDung_JButton = new javax.swing.JButton();
        AMF_UuTienThongBao_JPanel = new javax.swing.JPanel();
        AMF_UuTienThongBao_JLabel = new javax.swing.JLabel();
        AMF_UuTienThongBao_JToggleButton = new javax.swing.JToggleButton();
        AMF_TuDongXacNhanSuDung_JPanel = new javax.swing.JPanel();
        AMF_TuDongXacNhanSuDung_JLabel = new javax.swing.JLabel();
        AMF_TuDongXacNhanSuDung_JToggleButton = new javax.swing.JToggleButton();
        AMF_KhoangThoiGianLapThongBao_JPanel = new javax.swing.JPanel();
        AMF_KhoangThoiGianLapThongBao_JLabel = new javax.swing.JLabel();
        AMF_KhoangThoiGianLapThongBao_JSpinner = new javax.swing.JSpinner();
        AMF_QuanLySoLuongThuoc_JPanel = new javax.swing.JPanel();
        AMF_QuanLySoLuongThuoc_JLabel = new javax.swing.JLabel();
        AMF_HienCo_JLabel = new javax.swing.JLabel();
        AMF_HienCo_JSpinner = new javax.swing.JSpinner();
        AMF_NhacNho_JLabel = new javax.swing.JLabel();
        AMF_NhacNho_JSpinner = new javax.swing.JSpinner();
        AMF_MocThoiGianSuDungThuoc_JPanel = new javax.swing.JPanel();
        AMF_MocThoiGianSuDungThuoc_Them_JButton = new javax.swing.JButton();
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner = new javax.swing.JSpinner();
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner = new javax.swing.JSpinner();
        AMF_AM_PM_JComboBox = new javax.swing.JComboBox<>();
        AMF_LieuSuDung_JLabel = new javax.swing.JLabel();
        AMF_LieuSuDung_JSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        AMF_Huy_JButton.setFont(new java.awt.Font("SF Mono", 0, 24)); // NOI18N
        AMF_Huy_JButton.setText("Hủy");
        AMF_Huy_JButton.setMaximumSize(new java.awt.Dimension(120, 40));
        AMF_Huy_JButton.setMinimumSize(new java.awt.Dimension(120, 40));
        AMF_Huy_JButton.setPreferredSize(new java.awt.Dimension(120, 40));
        AMF_Huy_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Huy_JButtonActionPerformed(evt);
            }
        });
        AMF_ThanhChucNang_JPanel.add(AMF_Huy_JButton);

        AMF_ThemDonThuocMoi_JLabel.setFont(new java.awt.Font("SF Mono", 0, 36)); // NOI18N
        AMF_ThemDonThuocMoi_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AMF_ThemDonThuocMoi_JLabel.setText("Thêm đơn thuốc mới");
        AMF_ThemDonThuocMoi_JLabel.setMaximumSize(new java.awt.Dimension(425, 40));
        AMF_ThemDonThuocMoi_JLabel.setMinimumSize(new java.awt.Dimension(425, 40));
        AMF_ThemDonThuocMoi_JLabel.setPreferredSize(new java.awt.Dimension(425, 40));
        AMF_ThanhChucNang_JPanel.add(AMF_ThemDonThuocMoi_JLabel);

        AMF_Them_JButton.setFont(new java.awt.Font("SF Mono", 0, 24)); // NOI18N
        AMF_Them_JButton.setText("Thêm");
        AMF_Them_JButton.setMaximumSize(new java.awt.Dimension(120, 40));
        AMF_Them_JButton.setMinimumSize(new java.awt.Dimension(120, 40));
        AMF_Them_JButton.setPreferredSize(new java.awt.Dimension(120, 40));
        AMF_Them_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Them_JButtonActionPerformed(evt);
            }
        });
        AMF_ThanhChucNang_JPanel.add(AMF_Them_JButton);

        AMF_NoiDungThemThuoc_JScrollPane.setBorder(null);
        AMF_NoiDungThemThuoc_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        AMF_NoiDungThemThuoc_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        AMF_KhungNoiDungThemThuoc_JPanel.setLayout(new java.awt.GridLayout(9, 1, 5, 5));

        AMF_Ten_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_Ten_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_Ten_JLabel.setText("Tên:");
        AMF_Ten_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_Ten_JPanel.add(AMF_Ten_JLabel);

        AMF_Ten_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_Ten_JTextField.setToolTipText("Không điền đơn vị vào tên thuốc\nViết liền tên thuốc (không dấu cách \" \")");
        AMF_Ten_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_Ten_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_Ten_JTextFieldActionPerformed(evt);
            }
        });
        AMF_Ten_JPanel.add(AMF_Ten_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_Ten_JPanel);

        AMF_DonVi_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_DonVi_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_DonVi_JLabel.setText("Đơn vị:");
        AMF_DonVi_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_DonVi_JPanel.add(AMF_DonVi_JLabel);

        AMF_DonVi_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_DonVi_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_DonVi_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_DonVi_JTextFieldActionPerformed(evt);
            }
        });
        AMF_DonVi_JPanel.add(AMF_DonVi_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_DonVi_JPanel);

        AMF_GhiChu_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_GhiChu_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_GhiChu_JLabel.setText("Ghi chú:");
        AMF_GhiChu_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_GhiChu_JPanel.add(AMF_GhiChu_JLabel);

        AMF_GhiChu_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_GhiChu_JTextField.setMaximumSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JTextField.setMinimumSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        AMF_GhiChu_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_GhiChu_JTextFieldActionPerformed(evt);
            }
        });
        AMF_GhiChu_JPanel.add(AMF_GhiChu_JTextField);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_GhiChu_JPanel);

        AMF_TanSuatSuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_TanSuatSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_TanSuatSuDung_JLabel.setText("Tần suất sử dụng thuốc:");
        AMF_TanSuatSuDung_JLabel.setMaximumSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JLabel.setMinimumSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JLabel);

        AMF_TanSuatSuDung_JComboBox.setFont(new java.awt.Font("SF Mono", 0, 16)); // NOI18N
        AMF_TanSuatSuDung_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mỗi ngày", "Ngày trong tuần", "Ngày trong tháng", "Khi cần thiết" }));
        AMF_TanSuatSuDung_JComboBox.setMaximumSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.setMinimumSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.setPreferredSize(new java.awt.Dimension(250, 30));
        AMF_TanSuatSuDung_JComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                AMF_TanSuatSuDung_JComboBoxItemStateChanged(evt);
            }
        });
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JComboBox);

        AMF_TanSuatSuDung_JButton.setText("...");
        AMF_TanSuatSuDung_JButton.setMaximumSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.setMinimumSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.setPreferredSize(new java.awt.Dimension(40, 30));
        AMF_TanSuatSuDung_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_TanSuatSuDung_JButtonActionPerformed(evt);
            }
        });
        AMF_TanSuatSuDung_JPanel.add(AMF_TanSuatSuDung_JButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_TanSuatSuDung_JPanel);

        AMF_UuTienThongBao_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_UuTienThongBao_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_UuTienThongBao_JLabel.setText("Đặt mức độ ưu tiên thông báo cao hơn:");
        AMF_UuTienThongBao_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_UuTienThongBao_JPanel.add(AMF_UuTienThongBao_JLabel);

        AMF_UuTienThongBao_JToggleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AMF_UuTienThongBao_JToggleButton.setText("Y/N");
        AMF_UuTienThongBao_JToggleButton.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_UuTienThongBao_JToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_UuTienThongBao_JToggleButtonActionPerformed(evt);
            }
        });
        AMF_UuTienThongBao_JPanel.add(AMF_UuTienThongBao_JToggleButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_UuTienThongBao_JPanel);

        AMF_TuDongXacNhanSuDung_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_TuDongXacNhanSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_TuDongXacNhanSuDung_JLabel.setText("Tự động xác nhận sử dụng thuốc:");
        AMF_TuDongXacNhanSuDung_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_TuDongXacNhanSuDung_JPanel.add(AMF_TuDongXacNhanSuDung_JLabel);

        AMF_TuDongXacNhanSuDung_JToggleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AMF_TuDongXacNhanSuDung_JToggleButton.setText("Y/N");
        AMF_TuDongXacNhanSuDung_JToggleButton.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_TuDongXacNhanSuDung_JToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed(evt);
            }
        });
        AMF_TuDongXacNhanSuDung_JPanel.add(AMF_TuDongXacNhanSuDung_JToggleButton);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_TuDongXacNhanSuDung_JPanel);

        AMF_KhoangThoiGianLapThongBao_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_KhoangThoiGianLapThongBao_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_KhoangThoiGianLapThongBao_JLabel.setText("Khoảng thời gian lặp thông báo: ");
        AMF_KhoangThoiGianLapThongBao_JLabel.setMaximumSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JLabel.setMinimumSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JLabel.setPreferredSize(new java.awt.Dimension(410, 30));
        AMF_KhoangThoiGianLapThongBao_JPanel.add(AMF_KhoangThoiGianLapThongBao_JLabel);

        AMF_KhoangThoiGianLapThongBao_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_KhoangThoiGianLapThongBao_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setFocusable(false);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_KhoangThoiGianLapThongBao_JSpinner.setRequestFocusEnabled(false);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setValue(5);
        AMF_KhoangThoiGianLapThongBao_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_KhoangThoiGianLapThongBao_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel KhoangThoiGianLapThongBao_model = new SpinnerNumberModel(5, 5, 60, 5);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setModel(KhoangThoiGianLapThongBao_model);
        AMF_KhoangThoiGianLapThongBao_JPanel.add(AMF_KhoangThoiGianLapThongBao_JSpinner);
        JComponent editor_KhoangThoiGianLapThongBao = AMF_KhoangThoiGianLapThongBao_JSpinner.getEditor();
        JFormattedTextField tf_KhoangThoiGianLapThongBao = ((JSpinner.DefaultEditor) editor_KhoangThoiGianLapThongBao).getTextField();
        tf_KhoangThoiGianLapThongBao.setEditable(false);
        tf_KhoangThoiGianLapThongBao.setColumns(3);
        tf_KhoangThoiGianLapThongBao.setHorizontalAlignment(JTextField.CENTER);
        AMF_KhoangThoiGianLapThongBao_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_KhoangThoiGianLapThongBao_JPanel);

        AMF_QuanLySoLuongThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_QuanLySoLuongThuoc_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_QuanLySoLuongThuoc_JLabel.setText("Quản lý số lượng thuốc:");
        AMF_QuanLySoLuongThuoc_JLabel.setMaximumSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JLabel.setMinimumSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JLabel.setPreferredSize(new java.awt.Dimension(315, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_QuanLySoLuongThuoc_JLabel);

        AMF_HienCo_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_HienCo_JLabel.setText("Hiện có");
        AMF_HienCo_JLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_HienCo_JLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_HienCo_JLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_HienCo_JLabel);

        AMF_HienCo_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_HienCo_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_HienCo_JSpinner.setFocusable(false);
        AMF_HienCo_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_HienCo_JSpinner.setRequestFocusEnabled(false);
        AMF_HienCo_JSpinner.setValue(1);
        AMF_HienCo_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_HienCo_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel HienCo_model = new SpinnerNumberModel(1, 1, 100, 1);
        AMF_HienCo_JSpinner.setModel(HienCo_model);
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_HienCo_JSpinner);
        JComponent editor_HienCo = AMF_HienCo_JSpinner.getEditor();
        JFormattedTextField tf_HienCo = ((JSpinner.DefaultEditor) editor_HienCo).getTextField();
        tf_HienCo.setEditable(false);
        tf_HienCo.setColumns(3);
        tf_HienCo.setHorizontalAlignment(JTextField.CENTER);
        AMF_HienCo_JSpinner.setSize(64, 32);

        AMF_NhacNho_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_NhacNho_JLabel.setText("Nhắc nhở");
        AMF_NhacNho_JLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_NhacNho_JLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_NhacNho_JLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_NhacNho_JLabel);

        AMF_NhacNho_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_NhacNho_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_NhacNho_JSpinner.setFocusable(false);
        AMF_NhacNho_JSpinner.setMaximumSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setMinimumSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setPreferredSize(new java.awt.Dimension(70, 30));
        AMF_NhacNho_JSpinner.setRequestFocusEnabled(false);
        AMF_NhacNho_JSpinner.setValue(1);
        AMF_NhacNho_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_NhacNho_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel NhacNho_model = new SpinnerNumberModel(1, 1, 100, 1);
        AMF_NhacNho_JSpinner.setModel(NhacNho_model);
        AMF_QuanLySoLuongThuoc_JPanel.add(AMF_NhacNho_JSpinner);
        JComponent editor_NhacNho = AMF_NhacNho_JSpinner.getEditor();
        JFormattedTextField tf_NhacNho = ((JSpinner.DefaultEditor) editor_NhacNho).getTextField();
        tf_NhacNho.setEditable(false);
        tf_NhacNho.setColumns(3);
        tf_NhacNho.setHorizontalAlignment(JTextField.CENTER);
        AMF_NhacNho_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_QuanLySoLuongThuoc_JPanel);

        AMF_MocThoiGianSuDungThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        AMF_MocThoiGianSuDungThuoc_Them_JButton.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setText("Thêm");
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Them_JButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked(evt);
            }
        });
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Them_JButton);

        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setFocusable(false);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setRequestFocusEnabled(false);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_MocThoiGianSuDungThuoc_Gio_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel Gio_model = new SpinnerNumberModel(0, 0, 12, 1);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setModel(Gio_model);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Gio_JSpinner);
        JComponent editor_Gio = AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.getEditor();
        JFormattedTextField tf_Gio = ((JSpinner.DefaultEditor) editor_Gio).getTextField();
        tf_Gio.setEditable(false);
        tf_Gio.setColumns(3);
        tf_Gio.setHorizontalAlignment(JTextField.CENTER);
        AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setSize(64, 32);

        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setFocusable(false);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setRequestFocusEnabled(false);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_MocThoiGianSuDungThuoc_Phut_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel Phut_model = new SpinnerNumberModel(0, 0, 60, 1);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setModel(Phut_model);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_Phut_JSpinner);
        JComponent editor_Phut = AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.getEditor();
        JFormattedTextField tf_Phut = ((JSpinner.DefaultEditor) editor_Phut).getTextField();
        tf_Phut.setEditable(false);
        tf_Phut.setColumns(3);
        tf_Phut.setHorizontalAlignment(JTextField.CENTER);
        AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setSize(64, 32);

        AMF_AM_PM_JComboBox.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_AM_PM_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AM", "PM" }));
        AMF_AM_PM_JComboBox.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_AM_PM_JComboBox.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_AM_PM_JComboBox.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_AM_PM_JComboBox);

        AMF_LieuSuDung_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_LieuSuDung_JLabel.setText("Liều sử dụng");
        AMF_LieuSuDung_JLabel.setMaximumSize(new java.awt.Dimension(140, 30));
        AMF_LieuSuDung_JLabel.setMinimumSize(new java.awt.Dimension(140, 30));
        AMF_LieuSuDung_JLabel.setPreferredSize(new java.awt.Dimension(180, 30));
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_LieuSuDung_JLabel);

        AMF_LieuSuDung_JSpinner.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        AMF_LieuSuDung_JSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AMF_LieuSuDung_JSpinner.setFocusable(false);
        AMF_LieuSuDung_JSpinner.setMaximumSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setMinimumSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setPreferredSize(new java.awt.Dimension(90, 30));
        AMF_LieuSuDung_JSpinner.setRequestFocusEnabled(false);
        AMF_LieuSuDung_JSpinner.setValue(1);
        AMF_LieuSuDung_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AMF_LieuSuDung_JSpinnerStateChanged(evt);
            }
        });
        SpinnerNumberModel LieuSuDung_model = new SpinnerNumberModel(1, 1, 100, 1);
        AMF_LieuSuDung_JSpinner.setModel(LieuSuDung_model);
        AMF_MocThoiGianSuDungThuoc_JPanel.add(AMF_LieuSuDung_JSpinner);
        JComponent editor_LieuSuDung = AMF_LieuSuDung_JSpinner.getEditor();
        JFormattedTextField tf_LieuSuDung = ((JSpinner.DefaultEditor) editor_LieuSuDung).getTextField();
        tf_LieuSuDung.setEditable(false);
        tf_LieuSuDung.setColumns(3);
        tf_LieuSuDung.setHorizontalAlignment(JTextField.CENTER);
        AMF_LieuSuDung_JSpinner.setSize(64, 32);

        AMF_KhungNoiDungThemThuoc_JPanel.add(AMF_MocThoiGianSuDungThuoc_JPanel);

        AMF_NoiDungThemThuoc_JScrollPane.setViewportView(AMF_KhungNoiDungThemThuoc_JPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AMF_ThanhChucNang_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(AMF_NoiDungThemThuoc_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AMF_ThanhChucNang_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AMF_NoiDungThemThuoc_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AMF_Huy_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Huy_JButtonActionPerformed
        this.mf.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_AMF_Huy_JButtonActionPerformed

    private void AMF_Them_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Them_JButtonActionPerformed
        String TenThuocVariableHolder = AMF_Ten_JTextField.getText();
		String DonViVariableHolder = AMF_DonVi_JTextField.getText();
		String GhiChuVariableHolder = AMF_GhiChu_JTextField.getText();
		String TanSuatChungVariableHolder = AMF_TanSuatSuDung_JComboBox.getSelectedItem().toString();
		String TanSuatCuTheVariableHolder = Specific_data;
		
		boolean UuTienThongBaoVariableHolder = false;
		if (AMF_UuTienThongBao_JToggleButton.isEnabled() == true) {
			UuTienThongBaoVariableHolder = AMF_UuTienThongBao_JToggleButton.isSelected();
		}
		
		boolean AutoConfirmVariableHolder = false;
		if (AMF_TuDongXacNhanSuDung_JToggleButton.isEnabled() == true) {
			AutoConfirmVariableHolder = AMF_TuDongXacNhanSuDung_JToggleButton.isSelected();
		}
		
		int KhoangThongBaoVariableHolder = Integer.parseInt(
				AMF_KhoangThoiGianLapThongBao_JSpinner.getValue().toString()
		);
		int SLHienCoVariableHolder = Integer.parseInt(
				AMF_HienCo_JSpinner.getValue().toString()
		);
		int SLNhacNhoVariableHolder = Integer.parseInt(
				AMF_NhacNho_JSpinner.getValue().toString()
		);
		
		List<List<Object>> MocThoiGianVariableHolder = new ArrayList<>();
		
		for (Component cpm: AMF_KhungNoiDungThemThuoc_JPanel.getComponents()) {
			if (cpm instanceof TimeStoneAdditionPanel timeStoneAdditionPanel) {
				MocThoiGianVariableHolder.add(timeStoneAdditionPanel.loadValue());
			}
		}
		
		List<Object> ls = new ArrayList<>();
		ls.add(AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.getValue());
		ls.add(AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.getValue());
		ls.add(AMF_AM_PM_JComboBox.getSelectedItem());
		ls.add(AMF_LieuSuDung_JSpinner.getValue());
		MocThoiGianVariableHolder.addFirst(ls);
		
		if (DEBUG == 1) {
			System.out.println(TenThuocVariableHolder);
			System.out.println(DonViVariableHolder);
			System.out.println(GhiChuVariableHolder);
			System.out.println(TanSuatChungVariableHolder);
			System.out.println(TanSuatCuTheVariableHolder);
			System.out.println(UuTienThongBaoVariableHolder);
			System.out.println(AutoConfirmVariableHolder);
			System.out.println(KhoangThongBaoVariableHolder);
			System.out.println(SLHienCoVariableHolder);
			System.out.println(SLNhacNhoVariableHolder);
			
			for (List<Object> ll: MocThoiGianVariableHolder) {
				for (Object o: ll) {
					System.out.println(o + " ");
				}
				System.out.println();
			}
		}
		MedicineObject mo = new MedicineObject(
				TenThuocVariableHolder,
				DonViVariableHolder, 
				GhiChuVariableHolder, 
				TanSuatChungVariableHolder, 
				TanSuatCuTheVariableHolder, 
				UuTienThongBaoVariableHolder,
				AutoConfirmVariableHolder, 
				KhoangThongBaoVariableHolder, 
				SLHienCoVariableHolder, 
				SLNhacNhoVariableHolder, 
				MocThoiGianVariableHolder
		);
		mo.writeJSON(this.UserName);
		
		this.mf.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_AMF_Them_JButtonActionPerformed

    private void AMF_Ten_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_Ten_JTextFieldActionPerformed
        if (checkIllegalCharacter(AMF_Ten_JTextField.getText(), patt)) {
				JOptionPane.showMessageDialog(this, "Tên thuốc không được phép tồn tại ký tự đặc biệt. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
				AMF_Ten_JTextField.setText("");
		}
    }//GEN-LAST:event_AMF_Ten_JTextFieldActionPerformed

    private void AMF_UuTienThongBao_JToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_UuTienThongBao_JToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_UuTienThongBao_JToggleButtonActionPerformed

    private void AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AMF_TuDongXacNhanSuDung_JToggleButtonActionPerformed

    private void AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked
      	TimeStoneAdditionPanel JP = new TimeStoneAdditionPanel(AMF_KhungNoiDungThemThuoc_JPanel);
		JP.setSize(AMF_MocThoiGianSuDungThuoc_JPanel.getSize());
        
        LayoutManager layout = AMF_KhungNoiDungThemThuoc_JPanel.getLayout();
        
        if (layout instanceof GridLayout) {
            ((GridLayout) layout).setColumns(1);
            ((GridLayout) layout).setRows(((GridLayout) layout).getRows() + 1);
            AMF_KhungNoiDungThemThuoc_JPanel.setLayout(layout);
            AMF_KhungNoiDungThemThuoc_JPanel.add(JP, -1);
            AMF_KhungNoiDungThemThuoc_JPanel.revalidate();
            AMF_KhungNoiDungThemThuoc_JPanel.repaint();
        }
        mf.refresh_call();
    }//GEN-LAST:event_AMF_MocThoiGianSuDungThuoc_Them_JButtonMouseClicked

    private void AMF_TanSuatSuDung_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_TanSuatSuDung_JButtonActionPerformed
        // TODO add your handling code here:
        if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Mỗi ngày")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false); 
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tuần")) {
			String previousData = Specific_data;
			
            Specific_data = JOptionPane.showInputDialog(this, "Nhập các ngày trong tuần bạn muốn\n(phân cách bằng dấu \",\"):\n" + "2: Thứ Hai, 3: Thứ Ba, 4: Thứ Tư\n5: Thứ Năm, 6: Thứ Sáu, 7: Thứ Bảy\n8: Chủ Nhật", "Lựa chọn ngày trong tuần", JOptionPane.QUESTION_MESSAGE, null, null, previousData).toString();
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tháng")) {
			String previousData = Specific_data;
            Specific_data = JOptionPane.showInputDialog(this, "Nhập các ngày trong tháng bạn muốn\n(phân cách bằng dấu \",\"): ", "Lựa chọn ngày trong tháng", JOptionPane.QUESTION_MESSAGE, null, null, previousData).toString();
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Khi cần thiết")) {
			AMF_TanSuatSuDung_JButton.setEnabled(false); 
        }
    }//GEN-LAST:event_AMF_TanSuatSuDung_JButtonActionPerformed

    private void AMF_TanSuatSuDung_JComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_AMF_TanSuatSuDung_JComboBoxItemStateChanged
        // TODO add your handling code here:
		AMF_TanSuatSuDung_JButton.setEnabled(false);
		AMF_UuTienThongBao_JToggleButton.setSelected(false);
		AMF_TuDongXacNhanSuDung_JToggleButton.setSelected(false);
		AMF_KhoangThoiGianLapThongBao_JSpinner.setValue(5);
        if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Mỗi ngày")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false);
			AMF_UuTienThongBao_JToggleButton.setEnabled(true);
			AMF_TuDongXacNhanSuDung_JToggleButton.setEnabled(true);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tuần")) {
			AMF_TanSuatSuDung_JButton.setEnabled(true);
			AMF_UuTienThongBao_JToggleButton.setEnabled(true);
			AMF_TuDongXacNhanSuDung_JToggleButton.setEnabled(true);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Ngày trong tháng")) {
			AMF_TanSuatSuDung_JButton.setEnabled(true);
			AMF_UuTienThongBao_JToggleButton.setEnabled(true);
			AMF_TuDongXacNhanSuDung_JToggleButton.setEnabled(true);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setEnabled(true);
        } else if (AMF_TanSuatSuDung_JComboBox.getSelectedItem().equals("Khi cần thiết")) {
            AMF_TanSuatSuDung_JButton.setEnabled(false);
			AMF_UuTienThongBao_JToggleButton.setEnabled(false);
			AMF_TuDongXacNhanSuDung_JToggleButton.setEnabled(false);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setEnabled(false);
        }
    }//GEN-LAST:event_AMF_TanSuatSuDung_JComboBoxItemStateChanged

    private void AMF_DonVi_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_DonVi_JTextFieldActionPerformed
        if (!checkUnit(AMF_DonVi_JTextField.getText())) {
			JOptionPane.showMessageDialog(this, "Đơn vị không đúng định dạng. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_DonVi_JTextField.setText("");
		}
    }//GEN-LAST:event_AMF_DonVi_JTextFieldActionPerformed

    private void AMF_GhiChu_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMF_GhiChu_JTextFieldActionPerformed
        if (checkIllegalCharacter(AMF_GhiChu_JTextField.getText(), patt)) {
			JOptionPane.showMessageDialog(this, "Ghi chú không được phép tồn tại ký tự đặc biệt. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_GhiChu_JTextField.setText("");
		}
    }//GEN-LAST:event_AMF_GhiChu_JTextFieldActionPerformed

    private void AMF_KhoangThoiGianLapThongBao_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_KhoangThoiGianLapThongBao_JSpinnerStateChanged
        if (Integer.parseInt(AMF_KhoangThoiGianLapThongBao_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Khoảng thời gian phải là số dương. Vui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_KhoangThoiGianLapThongBao_JSpinner.setValue(5);
		}
    }//GEN-LAST:event_AMF_KhoangThoiGianLapThongBao_JSpinnerStateChanged

    private void AMF_HienCo_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_HienCo_JSpinnerStateChanged
        if (Integer.parseInt(AMF_HienCo_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Lượng thuốc hiện có phải là số dương. Vui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_HienCo_JSpinner.setValue(1);
		}
    }//GEN-LAST:event_AMF_HienCo_JSpinnerStateChanged

    private void AMF_NhacNho_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_NhacNho_JSpinnerStateChanged
		if (Integer.parseInt(AMF_NhacNho_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Lượng thuốc nhắc nhở bổ sung phải là số dương. Vui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_NhacNho_JSpinner.setValue(1);
		}
    }//GEN-LAST:event_AMF_NhacNho_JSpinnerStateChanged

    private void AMF_MocThoiGianSuDungThuoc_Gio_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_MocThoiGianSuDungThuoc_Gio_JSpinnerStateChanged
        if (Integer.parseInt(AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Mốc giờ phải là số dương.\nVui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setValue(0);
		} else if (Integer.parseInt(AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.getValue().toString()) > 12) {
			JOptionPane.showMessageDialog(this, "Mốc giờ phải nằm trong khoảng 0 đến 12.\nVui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_MocThoiGianSuDungThuoc_Gio_JSpinner.setValue(12);
		}
    }//GEN-LAST:event_AMF_MocThoiGianSuDungThuoc_Gio_JSpinnerStateChanged

    private void AMF_MocThoiGianSuDungThuoc_Phut_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_MocThoiGianSuDungThuoc_Phut_JSpinnerStateChanged
        if (Integer.parseInt(AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Mốc phút phải là số dương.\nVui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setValue(0);
		} else if (Integer.parseInt(AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.getValue().toString()) > 60) {
			JOptionPane.showMessageDialog(this, "Mốc phút phải nằm trong khoảng 0 đến 60.\nVui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_MocThoiGianSuDungThuoc_Phut_JSpinner.setValue(60);
		}
    }//GEN-LAST:event_AMF_MocThoiGianSuDungThuoc_Phut_JSpinnerStateChanged

    private void AMF_LieuSuDung_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AMF_LieuSuDung_JSpinnerStateChanged
        if (Integer.parseInt(AMF_LieuSuDung_JSpinner.getValue().toString()) < 0) {
			JOptionPane.showMessageDialog(this, "Lượng thuốc nhắc nhở bổ sung phải là số dương. Vui lòng chọn lại", "Error", JOptionPane.ERROR_MESSAGE);
			AMF_LieuSuDung_JSpinner.setValue(1);
		}
    }//GEN-LAST:event_AMF_LieuSuDung_JSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMedicationFrame(mf, UserName).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AMF_AM_PM_JComboBox;
    private javax.swing.JLabel AMF_DonVi_JLabel;
    private javax.swing.JPanel AMF_DonVi_JPanel;
    private javax.swing.JTextField AMF_DonVi_JTextField;
    private javax.swing.JLabel AMF_GhiChu_JLabel;
    private javax.swing.JPanel AMF_GhiChu_JPanel;
    private javax.swing.JTextField AMF_GhiChu_JTextField;
    private javax.swing.JLabel AMF_HienCo_JLabel;
    private javax.swing.JSpinner AMF_HienCo_JSpinner;
    private javax.swing.JButton AMF_Huy_JButton;
    private javax.swing.JLabel AMF_KhoangThoiGianLapThongBao_JLabel;
    private javax.swing.JPanel AMF_KhoangThoiGianLapThongBao_JPanel;
    private javax.swing.JSpinner AMF_KhoangThoiGianLapThongBao_JSpinner;
    private javax.swing.JPanel AMF_KhungNoiDungThemThuoc_JPanel;
    private javax.swing.JLabel AMF_LieuSuDung_JLabel;
    private javax.swing.JSpinner AMF_LieuSuDung_JSpinner;
    private javax.swing.JSpinner AMF_MocThoiGianSuDungThuoc_Gio_JSpinner;
    private javax.swing.JPanel AMF_MocThoiGianSuDungThuoc_JPanel;
    private javax.swing.JSpinner AMF_MocThoiGianSuDungThuoc_Phut_JSpinner;
    private javax.swing.JButton AMF_MocThoiGianSuDungThuoc_Them_JButton;
    private javax.swing.JLabel AMF_NhacNho_JLabel;
    private javax.swing.JSpinner AMF_NhacNho_JSpinner;
    private javax.swing.JScrollPane AMF_NoiDungThemThuoc_JScrollPane;
    private javax.swing.JLabel AMF_QuanLySoLuongThuoc_JLabel;
    private javax.swing.JPanel AMF_QuanLySoLuongThuoc_JPanel;
    private javax.swing.JButton AMF_TanSuatSuDung_JButton;
    private javax.swing.JComboBox<String> AMF_TanSuatSuDung_JComboBox;
    private javax.swing.JLabel AMF_TanSuatSuDung_JLabel;
    private javax.swing.JPanel AMF_TanSuatSuDung_JPanel;
    private javax.swing.JLabel AMF_Ten_JLabel;
    private javax.swing.JPanel AMF_Ten_JPanel;
    private javax.swing.JTextField AMF_Ten_JTextField;
    private javax.swing.JPanel AMF_ThanhChucNang_JPanel;
    private javax.swing.JLabel AMF_ThemDonThuocMoi_JLabel;
    private javax.swing.JButton AMF_Them_JButton;
    private javax.swing.JLabel AMF_TuDongXacNhanSuDung_JLabel;
    private javax.swing.JPanel AMF_TuDongXacNhanSuDung_JPanel;
    private javax.swing.JToggleButton AMF_TuDongXacNhanSuDung_JToggleButton;
    private javax.swing.JLabel AMF_UuTienThongBao_JLabel;
    private javax.swing.JPanel AMF_UuTienThongBao_JPanel;
    private javax.swing.JToggleButton AMF_UuTienThongBao_JToggleButton;
    // End of variables declaration//GEN-END:variables
}
