/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import object.UserObject;

/**
 *
 * @author Hinno
 */
public class CreateAccountFrame extends javax.swing.JFrame {
    int DEBUG = 1;
    public static AuthenticationFrame af;
	public String charset = "<>?/.,:\";'{}|\\[\\]\\\\()!@#$%^&*\\-_+=~`";
	Pattern patt = Pattern.compile("[" + charset + "]");
    /**
     * Creates new form CreateAccountFrame
     */
    public CreateAccountFrame(AuthenticationFrame af) {
		this.af = af;
        FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
        initComponents();
        this.setFrameInCenter();
        this.setVisible(true);
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }
	
	public boolean checkIllegalCharacter(String inp, Pattern pat) {
		Matcher match = pat.matcher(inp);
		return match.find();
	}
	
	public boolean checkEmailValid(String email) {
		final Pattern EMAIL_REGEX = Pattern.compile("[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", Pattern.CASE_INSENSITIVE);
		return EMAIL_REGEX.matcher(email).matches();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CAF_IntermidiateContainer_JPanel = new javax.swing.JPanel();
        CAF_TaoTaiKhoan_JLabel = new javax.swing.JLabel();
        CAF_TenTaiKhoan_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_TenTaiKhoan_JLabel = new javax.swing.JLabel();
        CAF_TenTaiKhoan_JTextField = new javax.swing.JTextField();
        CAF_MatKhau_JlL_JTF_JPanel = new javax.swing.JPanel();
        CAF_MatKhau_JLabel = new javax.swing.JLabel();
        CAF_MatKhau_JPasswordField = new javax.swing.JPasswordField();
        CAF_XacNhanMatKhau_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_XacNhanMatKhau_JLabel = new javax.swing.JLabel();
        CAF_XacNhanMatKhau_JPasswordField = new javax.swing.JPasswordField();
        CAF_HoTen_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_HoTen_JLabel = new javax.swing.JLabel();
        CAF_HoTen_JTextField = new javax.swing.JTextField();
        CAF_Email_JL_JTF_JPanel = new javax.swing.JPanel();
        CAF_Email_JLabel = new javax.swing.JLabel();
        CAF_Email_JTextField = new javax.swing.JTextField();
        CAF_Tuoi_JL_JS_JPanel = new javax.swing.JPanel();
        CAF_Tuoi_JLabel = new javax.swing.JLabel();
        CAF_Tuoi_JSpinner = new javax.swing.JSpinner();
        CAF_KhuVucSinhSong_JL_JCB_JPanel = new javax.swing.JPanel();
        CAF_KhuVucSinhSong_JLabel = new javax.swing.JLabel();
        CAF_KhuVucSinhSong_JComboBox = new javax.swing.JComboBox<>();
        CAF_TienSuBenhLy_JL_JTA_JPanel = new javax.swing.JPanel();
        CAF_TienSuBenhLy_JLabel = new javax.swing.JLabel();
        CAF_TienSuBenhLy_JScrollPane = new javax.swing.JScrollPane();
        CAF_TienSuBenhLy_JTextArea = new javax.swing.JTextArea();
        CAF_Button_JPanel = new javax.swing.JPanel();
        CAF_TroLai_JButton = new javax.swing.JButton();
        CAF_XacNhan_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        CAF_TaoTaiKhoan_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 36)); // NOI18N
        CAF_TaoTaiKhoan_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CAF_TaoTaiKhoan_JLabel.setText("TẠO TÀI KHOẢN");

        CAF_TenTaiKhoan_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_TenTaiKhoan_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_TenTaiKhoan_JLabel.setText("Tên tài khoản:");
        CAF_TenTaiKhoan_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_TenTaiKhoan_JL_JTF_JPanel.add(CAF_TenTaiKhoan_JLabel);

        CAF_TenTaiKhoan_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_TenTaiKhoan_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        CAF_TenTaiKhoan_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAF_TenTaiKhoan_JTextFieldActionPerformed(evt);
            }
        });
        CAF_TenTaiKhoan_JL_JTF_JPanel.add(CAF_TenTaiKhoan_JTextField);

        CAF_MatKhau_JlL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_MatKhau_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_MatKhau_JLabel.setText("Mật khẩu:");
        CAF_MatKhau_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_MatKhau_JlL_JTF_JPanel.add(CAF_MatKhau_JLabel);

        CAF_MatKhau_JPasswordField.setPreferredSize(new java.awt.Dimension(385, 30));
        CAF_MatKhau_JlL_JTF_JPanel.add(CAF_MatKhau_JPasswordField);

        CAF_XacNhanMatKhau_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_XacNhanMatKhau_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_XacNhanMatKhau_JLabel.setText("Xác nhận mật khẩu:");
        CAF_XacNhanMatKhau_JL_JTF_JPanel.add(CAF_XacNhanMatKhau_JLabel);

        CAF_XacNhanMatKhau_JPasswordField.setPreferredSize(new java.awt.Dimension(385, 30));
        CAF_XacNhanMatKhau_JL_JTF_JPanel.add(CAF_XacNhanMatKhau_JPasswordField);

        CAF_HoTen_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_HoTen_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_HoTen_JLabel.setText("Họ tên:");
        CAF_HoTen_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_HoTen_JL_JTF_JPanel.add(CAF_HoTen_JLabel);

        CAF_HoTen_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_HoTen_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        CAF_HoTen_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAF_HoTen_JTextFieldActionPerformed(evt);
            }
        });
        CAF_HoTen_JL_JTF_JPanel.add(CAF_HoTen_JTextField);

        CAF_Email_JL_JTF_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_Email_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_Email_JLabel.setText("Email:");
        CAF_Email_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_Email_JL_JTF_JPanel.add(CAF_Email_JLabel);

        CAF_Email_JTextField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 14)); // NOI18N
        CAF_Email_JTextField.setPreferredSize(new java.awt.Dimension(385, 30));
        CAF_Email_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAF_Email_JTextFieldActionPerformed(evt);
            }
        });
        CAF_Email_JL_JTF_JPanel.add(CAF_Email_JTextField);

        CAF_Tuoi_JL_JS_JPanel.setPreferredSize(new java.awt.Dimension(670, 40));
        CAF_Tuoi_JL_JS_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_Tuoi_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_Tuoi_JLabel.setText("Tuổi:");
        CAF_Tuoi_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_Tuoi_JL_JS_JPanel.add(CAF_Tuoi_JLabel);

        CAF_Tuoi_JSpinner.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        CAF_Tuoi_JSpinner.setPreferredSize(new java.awt.Dimension(82, 30));
        CAF_Tuoi_JSpinner.setValue(15);
        CAF_Tuoi_JSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CAF_Tuoi_JSpinnerStateChanged(evt);
            }
        });
        CAF_Tuoi_JL_JS_JPanel.add(CAF_Tuoi_JSpinner);

        CAF_KhuVucSinhSong_JL_JCB_JPanel.setPreferredSize(new java.awt.Dimension(670, 40));
        CAF_KhuVucSinhSong_JL_JCB_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        CAF_KhuVucSinhSong_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_KhuVucSinhSong_JLabel.setText("Khu vực sinh sống:");
        CAF_KhuVucSinhSong_JL_JCB_JPanel.add(CAF_KhuVucSinhSong_JLabel);

        CAF_KhuVucSinhSong_JComboBox.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        CAF_KhuVucSinhSong_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Miền Bắc", "Miền Trung", "Miền Nam", " " }));
        CAF_KhuVucSinhSong_JComboBox.setPreferredSize(new java.awt.Dimension(170, 30));
        CAF_KhuVucSinhSong_JL_JCB_JPanel.add(CAF_KhuVucSinhSong_JComboBox);

        CAF_TienSuBenhLy_JL_JTA_JPanel.setPreferredSize(new java.awt.Dimension(670, 110));

        CAF_TienSuBenhLy_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_TienSuBenhLy_JLabel.setText("Tiền sử bệnh lý:");
        CAF_TienSuBenhLy_JLabel.setPreferredSize(new java.awt.Dimension(270, 30));
        CAF_TienSuBenhLy_JL_JTA_JPanel.add(CAF_TienSuBenhLy_JLabel);

        CAF_TienSuBenhLy_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        CAF_TienSuBenhLy_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        CAF_TienSuBenhLy_JScrollPane.setMaximumSize(new java.awt.Dimension(385, 100));
        CAF_TienSuBenhLy_JScrollPane.setMinimumSize(new java.awt.Dimension(385, 100));
        CAF_TienSuBenhLy_JScrollPane.setPreferredSize(new java.awt.Dimension(385, 100));

        CAF_TienSuBenhLy_JTextArea.setColumns(20);
        CAF_TienSuBenhLy_JTextArea.setRows(10);
        CAF_TienSuBenhLy_JTextArea.setMaximumSize(new java.awt.Dimension(385, 100));
        CAF_TienSuBenhLy_JTextArea.setMinimumSize(new java.awt.Dimension(385, 100));
        CAF_TienSuBenhLy_JScrollPane.setViewportView(CAF_TienSuBenhLy_JTextArea);

        CAF_TienSuBenhLy_JL_JTA_JPanel.add(CAF_TienSuBenhLy_JScrollPane);

        CAF_Button_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        CAF_TroLai_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_TroLai_JButton.setText("Trở lại");
        CAF_TroLai_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAF_TroLai_JButtonActionPerformed(evt);
            }
        });
        CAF_Button_JPanel.add(CAF_TroLai_JButton);

        CAF_XacNhan_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 25)); // NOI18N
        CAF_XacNhan_JButton.setText("Xác nhận");
        CAF_XacNhan_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAF_XacNhan_JButtonActionPerformed(evt);
            }
        });
        CAF_Button_JPanel.add(CAF_XacNhan_JButton);

        javax.swing.GroupLayout CAF_IntermidiateContainer_JPanelLayout = new javax.swing.GroupLayout(CAF_IntermidiateContainer_JPanel);
        CAF_IntermidiateContainer_JPanel.setLayout(CAF_IntermidiateContainer_JPanelLayout);
        CAF_IntermidiateContainer_JPanelLayout.setHorizontalGroup(
            CAF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CAF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CAF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                        .addGroup(CAF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CAF_TaoTaiKhoan_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_TenTaiKhoan_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_MatKhau_JlL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_XacNhanMatKhau_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_HoTen_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_Email_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_Tuoi_JL_JS_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_TienSuBenhLy_JL_JTA_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CAF_KhuVucSinhSong_JL_JCB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CAF_Button_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CAF_IntermidiateContainer_JPanelLayout.setVerticalGroup(
            CAF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(CAF_TaoTaiKhoan_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_TenTaiKhoan_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_MatKhau_JlL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_XacNhanMatKhau_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_HoTen_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_Email_JL_JTF_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_Tuoi_JL_JS_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_TienSuBenhLy_JL_JTA_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_KhuVucSinhSong_JL_JCB_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAF_Button_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(CAF_IntermidiateContainer_JPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // connector for jdbc
    private Connection connect() {
        // connection parameter
        String dbURL = "jdbc:oracle:thin:@192.168.124.180:32772:XE";
        String driver = "oracle.jdbc.OracleDriver";
        Connection con = null;
        
        // catching error in connection
        try {
            // class loader
            Class.forName(driver);
            
            // connection
            con = DriverManager.getConnection(dbURL, "c##shanghuang", "181105");

            // debug block
            if (con != null) {
                if (DEBUG == 1) {
                    System.out.println("Kết nối đến cơ sử dữ liệu thành công");
                }
            }
        } catch(SQLException se) { 
            // sql exception
            System.out.println(se.getMessage());
        } catch (ClassNotFoundException ex) { 
            // class exception
            Logger.getLogger(CreateAccountFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Return connection
        if (con != null) {
            return con;
        } else {
            return null;
        }
    }
    
    private void CAF_XacNhan_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAF_XacNhan_JButtonActionPerformed
        String UsernameVariableHolder = CAF_TenTaiKhoan_JTextField.getText();
        String PasswordVariableHolder = new String(CAF_MatKhau_JPasswordField.getPassword());
        String PasswordConfirmVariableHolder = new String(CAF_XacNhanMatKhau_JPasswordField.getPassword());
        String HoTenVariableHolder = CAF_HoTen_JTextField.getText();
        String EmailVariableHolder = CAF_Email_JTextField.getText();
        int AgeVariableHolder = Integer.parseInt(CAF_Tuoi_JSpinner.getValue().toString());
		CAF_TienSuBenhLy_JTextArea.selectAll();
        String TienSuVariableHolder = CAF_TienSuBenhLy_JTextArea.getSelectedText();
        String KhuVucVariableHolder = CAF_KhuVucSinhSong_JComboBox.getSelectedItem().toString();
        
        if (!PasswordVariableHolder.contentEquals(PasswordConfirmVariableHolder)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu và xác nhận mật khẩu không khớp. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Create connection
            Connection con = connect();

            if (con == null) {
                // debug block
                if (DEBUG == 1) {
                    System.out.println("Không thể kết nối đến cơ sử dữ liệu");
                }
            } else {
                // query parameter
                boolean result = false;
                String query = "INSERT INTO CANHAN(USERNAME, MATKHAU, HOTEN, EMAIL, TUOI, KVSONG, TIENSUBENHLY) VALUES (?, ?, ?, ?, ?, ?, ?)";

                // catching error in query execution
                try {
                    // load parameter in to query
                    PreparedStatement ps = con.prepareStatement(query);
                    ps.setString(1, UsernameVariableHolder);
                    ps.setString(2, PasswordVariableHolder);
                    ps.setString(3, HoTenVariableHolder);
                    ps.setString(4, EmailVariableHolder);
                    ps.setString(5, String.valueOf(AgeVariableHolder));
                    ps.setString(6, KhuVucVariableHolder);
                    ps.setString(7, TienSuVariableHolder);
                    
                    if (DEBUG == 1) {
                        System.out.println(UsernameVariableHolder);
                        System.out.println(PasswordVariableHolder);
                        System.out.println(HoTenVariableHolder);
                        System.out.println(EmailVariableHolder);
                        System.out.println(String.valueOf(AgeVariableHolder));
                        System.out.println(KhuVucVariableHolder);
                        System.out.println(TienSuVariableHolder);
                    }

                    // execute and return boolean value to confirm connection
                    ps.executeUpdate();
                    result = true;
                    con.close();
                } catch (SQLException se) {
                    // SQL Exception
                    System.out.println(se.getMessage());
                }

                // checking connection confirm
                if (result == false) {
                    // error display
                    JOptionPane.showMessageDialog(this, "Tạo tài khoản thất bại", "Error", JOptionPane.ERROR_MESSAGE);

                    // debug block
                    if (DEBUG == 1) {
                        System.out.println("userview.CreateAccountFrame.CAF_XacNhan_JButtonActionPerformed(): Fail to create account");
                    }
                } else {
                    // success display
                    JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công", "Success", JOptionPane.INFORMATION_MESSAGE);
					UserObject uo = new UserObject(
						UsernameVariableHolder, 
						HoTenVariableHolder, 
						EmailVariableHolder, 
						KhuVucVariableHolder, 
						TienSuVariableHolder, 
						AgeVariableHolder
					);
					createDir();
					
					uo.writeJSON();
					
                    // debug block
                    if (DEBUG == 1) {
                        System.out.println("userview.CreateAccountFrame.CAF_XacNhan_JButtonActionPerformed(): Success to create account");
                    }
                }
            }
        }

        this.af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CAF_XacNhan_JButtonActionPerformed

	private void createDir() {
		String parentFolder = "/home/shanghuang/SMM_STO_" + CAF_TenTaiKhoan_JTextField.getText().trim();
        String[] subFolders = {"UO", "MO", "SO", "30HO", "TO", "RO", "OSRO"};

        // 1. Tạo thư mục gốc STO
        File stoFolder = new File(parentFolder);

        if (!stoFolder.exists()) {
            if (stoFolder.mkdirs()) { // Sử dụng mkdirs() để tạo cả thư mục cha (nếu cần)
                System.out.println("Thư mục " + parentFolder + " đã được tạo.");
            } else {
                System.err.println("Không thể tạo thư mục " + parentFolder);
                return; // Dừng chương trình nếu không tạo được thư mục gốc
            }
        } else {
            System.out.println("Thư mục " + parentFolder + " đã tồn tại.");
        }


        // 2. Tạo các thư mục con bên trong STO
        for (String subFolder : subFolders) {
            File folder = new File(stoFolder, subFolder); // Tạo File object cho thư mục con

            if (!folder.exists()) {
                if (folder.mkdir()) { // Sử dụng mkdir() để tạo một thư mục duy nhất
                    System.out.println("Thư mục " + subFolder + " đã được tạo trong " + parentFolder);
                } else {
                    System.err.println("Không thể tạo thư mục " + subFolder + " trong " + parentFolder);
                }
            } else {
                System.out.println("Thư mục " + subFolder + " đã tồn tại trong " + parentFolder);
            }
        }

        System.out.println("Hoàn thành!");
	}
	
    private void CAF_TroLai_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAF_TroLai_JButtonActionPerformed
        // TODO add your handling code here:
        this.af.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CAF_TroLai_JButtonActionPerformed

    private void CAF_Tuoi_JSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CAF_Tuoi_JSpinnerStateChanged
        // TODO add your handling code here:
        int age = Integer.parseInt(CAF_Tuoi_JSpinner.getValue().toString());
        if (age <= 0) {
            JOptionPane.showMessageDialog(this, "Tuổi phải là số dương", "Error", JOptionPane.ERROR_MESSAGE);
            CAF_Tuoi_JSpinner.setValue(15);
        } else if (1 < age && age < 12) {
            JOptionPane.showMessageDialog(this, "Cân nhắc sử dụng ứng dụng với độ tuổi này", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_CAF_Tuoi_JSpinnerStateChanged

    private void CAF_TenTaiKhoan_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAF_TenTaiKhoan_JTextFieldActionPerformed
        // TODO add your handling code here:
        int len = CAF_TenTaiKhoan_JTextField.getText().length();
        if (len <= 10) {
            
        } else {
            JOptionPane.showMessageDialog(this, "Độ dài giới hạn trong 10 ký tự", "Error", JOptionPane.ERROR_MESSAGE);
        }
		
		if (checkIllegalCharacter(CAF_TenTaiKhoan_JTextField.getText(), patt)) {
				JOptionPane.showMessageDialog(this, "Username không được phép tồn tại ký tự đặc biệt. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_CAF_TenTaiKhoan_JTextFieldActionPerformed

    private void CAF_HoTen_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAF_HoTen_JTextFieldActionPerformed
        if (checkIllegalCharacter(CAF_HoTen_JTextField.getText(), patt)) {
				JOptionPane.showMessageDialog(this, "Họ tên không được phép tồn tại ký tự đặc biệt. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_CAF_HoTen_JTextFieldActionPerformed

    private void CAF_Email_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAF_Email_JTextFieldActionPerformed
        
		if (!checkEmailValid(CAF_Email_JTextField.getText())) {
				JOptionPane.showMessageDialog(this, "Email không đúng định dạng. Vui lòng nhập lại", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }//GEN-LAST:event_CAF_Email_JTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccountFrame(af).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CAF_Button_JPanel;
    private javax.swing.JPanel CAF_Email_JL_JTF_JPanel;
    private javax.swing.JLabel CAF_Email_JLabel;
    private javax.swing.JTextField CAF_Email_JTextField;
    private javax.swing.JPanel CAF_HoTen_JL_JTF_JPanel;
    private javax.swing.JLabel CAF_HoTen_JLabel;
    private javax.swing.JTextField CAF_HoTen_JTextField;
    private javax.swing.JPanel CAF_IntermidiateContainer_JPanel;
    private javax.swing.JComboBox<String> CAF_KhuVucSinhSong_JComboBox;
    private javax.swing.JPanel CAF_KhuVucSinhSong_JL_JCB_JPanel;
    private javax.swing.JLabel CAF_KhuVucSinhSong_JLabel;
    private javax.swing.JLabel CAF_MatKhau_JLabel;
    private javax.swing.JPasswordField CAF_MatKhau_JPasswordField;
    private javax.swing.JPanel CAF_MatKhau_JlL_JTF_JPanel;
    private javax.swing.JLabel CAF_TaoTaiKhoan_JLabel;
    private javax.swing.JPanel CAF_TenTaiKhoan_JL_JTF_JPanel;
    private javax.swing.JLabel CAF_TenTaiKhoan_JLabel;
    private javax.swing.JTextField CAF_TenTaiKhoan_JTextField;
    private javax.swing.JPanel CAF_TienSuBenhLy_JL_JTA_JPanel;
    private javax.swing.JLabel CAF_TienSuBenhLy_JLabel;
    private javax.swing.JScrollPane CAF_TienSuBenhLy_JScrollPane;
    private javax.swing.JTextArea CAF_TienSuBenhLy_JTextArea;
    private javax.swing.JButton CAF_TroLai_JButton;
    private javax.swing.JPanel CAF_Tuoi_JL_JS_JPanel;
    private javax.swing.JLabel CAF_Tuoi_JLabel;
    private javax.swing.JSpinner CAF_Tuoi_JSpinner;
    private javax.swing.JPanel CAF_XacNhanMatKhau_JL_JTF_JPanel;
    private javax.swing.JLabel CAF_XacNhanMatKhau_JLabel;
    private javax.swing.JPasswordField CAF_XacNhanMatKhau_JPasswordField;
    private javax.swing.JButton CAF_XacNhan_JButton;
    // End of variables declaration//GEN-END:variables
}
