/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author shanghuang
 */
public class ForgotPasswordFrame extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPasswordFrame
     */
    public ForgotPasswordFrame() {
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
        this.setFrameInCenter();
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FPF_IntermidiateContainer_JPanel = new javax.swing.JPanel();
        FPF_NhapMaOTPTuEmail_JLabel = new javax.swing.JLabel();
        FPF_OTPInput_JTextField = new javax.swing.JTextField();
        FPF_OTPResend_JLabel = new javax.swing.JLabel();
        FPF_TimeCountBackward_JLabel = new javax.swing.JLabel();
        FPF_XacNhanOTP_JButton = new javax.swing.JButton();
        FPF_Separator_JSeparator = new javax.swing.JSeparator();
        FPF_NewPassword_JLabel = new javax.swing.JLabel();
        FPF_NewPasswordInput_JTextField = new javax.swing.JTextField();
        FPF_NewPasswordConfirm_JLabel = new javax.swing.JLabel();
        FPF_NewPasswordConfirmInput_JTextField = new javax.swing.JTextField();
        FPF_Finish_JButton = new javax.swing.JButton();
        FPF_Return_JButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FPF_NhapMaOTPTuEmail_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 30)); // NOI18N
        FPF_NhapMaOTPTuEmail_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FPF_NhapMaOTPTuEmail_JLabel.setText("Nhập mã OTP từ Email đăng ký");

        FPF_OTPInput_JTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FPF_OTPResend_JLabel.setText("Chưa nhận được? Hãy nhấn vào đây!");

        FPF_TimeCountBackward_JLabel.setText("60s");

        FPF_XacNhanOTP_JButton.setText("Xác nhận");

        FPF_NewPassword_JLabel.setText("Mật khẩu mới:");
        FPF_NewPassword_JLabel.setEnabled(false);

        FPF_NewPasswordInput_JTextField.setEnabled(false);

        FPF_NewPasswordConfirm_JLabel.setText("Xác nhận mật khẩu mới:");
        FPF_NewPasswordConfirm_JLabel.setEnabled(false);

        FPF_NewPasswordConfirmInput_JTextField.setEnabled(false);

        FPF_Finish_JButton.setText("Hoàn tất");
        FPF_Finish_JButton.setEnabled(false);

        FPF_Return_JButton.setText("Trở về");

        javax.swing.GroupLayout FPF_IntermidiateContainer_JPanelLayout = new javax.swing.GroupLayout(FPF_IntermidiateContainer_JPanel);
        FPF_IntermidiateContainer_JPanel.setLayout(FPF_IntermidiateContainer_JPanelLayout);
        FPF_IntermidiateContainer_JPanelLayout.setHorizontalGroup(
            FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FPF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FPF_Separator_JSeparator)
                    .addComponent(FPF_NhapMaOTPTuEmail_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FPF_OTPInput_JTextField)
                    .addComponent(FPF_NewPassword_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FPF_NewPasswordInput_JTextField)
                    .addComponent(FPF_NewPasswordConfirm_JLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FPF_NewPasswordConfirmInput_JTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FPF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                            .addComponent(FPF_Return_JButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FPF_Finish_JButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FPF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FPF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                                    .addComponent(FPF_OTPResend_JLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(FPF_TimeCountBackward_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(FPF_XacNhanOTP_JButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        FPF_IntermidiateContainer_JPanelLayout.setVerticalGroup(
            FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FPF_IntermidiateContainer_JPanelLayout.createSequentialGroup()
                .addComponent(FPF_NhapMaOTPTuEmail_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_OTPInput_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FPF_OTPResend_JLabel)
                    .addComponent(FPF_TimeCountBackward_JLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_XacNhanOTP_JButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_Separator_JSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_NewPassword_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_NewPasswordInput_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_NewPasswordConfirm_JLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FPF_NewPasswordConfirmInput_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FPF_IntermidiateContainer_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FPF_Finish_JButton)
                    .addComponent(FPF_Return_JButton))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FPF_IntermidiateContainer_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FPF_IntermidiateContainer_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FPF_Finish_JButton;
    private javax.swing.JPanel FPF_IntermidiateContainer_JPanel;
    private javax.swing.JTextField FPF_NewPasswordConfirmInput_JTextField;
    private javax.swing.JLabel FPF_NewPasswordConfirm_JLabel;
    private javax.swing.JTextField FPF_NewPasswordInput_JTextField;
    private javax.swing.JLabel FPF_NewPassword_JLabel;
    private javax.swing.JLabel FPF_NhapMaOTPTuEmail_JLabel;
    private javax.swing.JTextField FPF_OTPInput_JTextField;
    private javax.swing.JLabel FPF_OTPResend_JLabel;
    private javax.swing.JButton FPF_Return_JButton;
    private javax.swing.JSeparator FPF_Separator_JSeparator;
    private javax.swing.JLabel FPF_TimeCountBackward_JLabel;
    private javax.swing.JButton FPF_XacNhanOTP_JButton;
    // End of variables declaration//GEN-END:variables
}
