/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;
import java.awt.*;
/**
 *
 * @author shanghuang
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
        this.setFrameInCenter();
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MF_IntermidiateContainer_JTabbedPane = new javax.swing.JTabbedPane();
        MF_HomNay_JPanel = new javax.swing.JPanel();
        MF_NoiDungHomNay_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungHomNay_JPanel = new javax.swing.JPanel();
        MF_ThanhChucNangHomNay_JPanel = new javax.swing.JPanel();
        MF_BoQua_JButton = new javax.swing.JButton();
        MF_SuDung1Lan_JButton = new javax.swing.JButton();
        MF_XacNhan_JButton = new javax.swing.JButton();
        MF_DanhMucThuoc_JPanel = new javax.swing.JPanel();
        MF_NoiDungDanhMucThuoc_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungDanhMucThuoc_JPanel = new javax.swing.JPanel();
        MF_ThanhChucNangDanhMucThuoc_JPanel = new javax.swing.JPanel();
        MF_Them_JButton = new javax.swing.JButton();
        MF_Xoa_JButton = new javax.swing.JButton();
        MF_TraCuu_JButton = new javax.swing.JButton();
        MF_TraCuu_JTextField = new javax.swing.JTextField();
        MF_XuatDanhMuc_JButton = new javax.swing.JButton();
        MF_NhapDanhMuc_JButton = new javax.swing.JButton();
        MF_LichSu_JPanel = new javax.swing.JPanel();
        MF_NoiDungLichSu_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungLichSu_JPanel = new javax.swing.JPanel();
        MF_ThanhChucNangLichSu_JPanel = new javax.swing.JPanel();
        MF_TraCuuThuocSuDung_JLabel = new javax.swing.JLabel();
        MF_TraCuuThuocSuDung_JTextField = new javax.swing.JTextField();
        MF_TraCuuThuocSuDung_JButton = new javax.swing.JButton();
        MF_XuatLichSu_JButton = new javax.swing.JButton();
        MF_BaoCaoThoiQuen_JButton = new javax.swing.JButton();
        MF_TraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_JSeparator = new javax.swing.JSeparator();
        MF_NoiDungTraCuuOnline_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungTraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_ThanhChucNangTraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_TenThuoc_JLabel = new javax.swing.JLabel();
        MF_TraCuuOnline_JTextField = new javax.swing.JTextField();
        MF_TraCuuOnline_JButton = new javax.swing.JButton();
        MF_KiemTraTuongTacThuoc_JPanel = new javax.swing.JPanel();
        MF_NoiDungKiemTraTuongTacThuoc_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungKiemTraTuongTacThuoc_JTextArea = new javax.swing.JTextArea();
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane = new javax.swing.JPanel();
        MF_TenThuoc1_JLabel = new javax.swing.JLabel();
        MF_TenThuoc1_JTextField = new javax.swing.JTextField();
        MF_KiemTra_JButton = new javax.swing.JButton();
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane = new javax.swing.JPanel();
        MF_TenThuoc2_JLabel = new javax.swing.JLabel();
        MF_TenThuoc2_JTextField = new javax.swing.JTextField();
        MF_XoaTatCa_JButton = new javax.swing.JButton();
        MF_Chon_JMenuBar = new javax.swing.JMenuBar();
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu = new javax.swing.JMenu();
        MF_CaiDat_JMenuItem = new javax.swing.JMenuItem();
        MF_VePhanMem_JMenuItem = new javax.swing.JMenuItem();
        MF_VeCaNhan_JMenuItem = new javax.swing.JMenuItem();
        MF_Thoat_JMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý dược phẩm cá nhân");
        setResizable(false);

        MF_NoiDungHomNay_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MF_NoiDungHomNay_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout MF_KhungNoiDungHomNay_JPanelLayout = new javax.swing.GroupLayout(MF_KhungNoiDungHomNay_JPanel);
        MF_KhungNoiDungHomNay_JPanel.setLayout(MF_KhungNoiDungHomNay_JPanelLayout);
        MF_KhungNoiDungHomNay_JPanelLayout.setHorizontalGroup(
            MF_KhungNoiDungHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
        );
        MF_KhungNoiDungHomNay_JPanelLayout.setVerticalGroup(
            MF_KhungNoiDungHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );

        MF_NoiDungHomNay_JScrollPane.setViewportView(MF_KhungNoiDungHomNay_JPanel);

        MF_ThanhChucNangHomNay_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        MF_BoQua_JButton.setText("Bỏ qua");
        MF_BoQua_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_BoQua_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangHomNay_JPanel.add(MF_BoQua_JButton);

        MF_SuDung1Lan_JButton.setText("Sử dụng 1 lần");
        MF_SuDung1Lan_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_SuDung1Lan_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangHomNay_JPanel.add(MF_SuDung1Lan_JButton);

        MF_XacNhan_JButton.setText("Xác nhận");
        MF_ThanhChucNangHomNay_JPanel.add(MF_XacNhan_JButton);

        javax.swing.GroupLayout MF_HomNay_JPanelLayout = new javax.swing.GroupLayout(MF_HomNay_JPanel);
        MF_HomNay_JPanel.setLayout(MF_HomNay_JPanelLayout);
        MF_HomNay_JPanelLayout.setHorizontalGroup(
            MF_HomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MF_NoiDungHomNay_JScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_HomNay_JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MF_ThanhChucNangHomNay_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );
        MF_HomNay_JPanelLayout.setVerticalGroup(
            MF_HomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_HomNay_JPanelLayout.createSequentialGroup()
                .addComponent(MF_NoiDungHomNay_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MF_ThanhChucNangHomNay_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Hôm nay", MF_HomNay_JPanel);

        MF_NoiDungDanhMucThuoc_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MF_NoiDungDanhMucThuoc_JScrollPane.setToolTipText("");
        MF_NoiDungDanhMucThuoc_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        MF_KhungNoiDungDanhMucThuoc_JPanel.setLayout(new java.awt.GridLayout(1, 1));
        MF_NoiDungDanhMucThuoc_JScrollPane.setViewportView(MF_KhungNoiDungDanhMucThuoc_JPanel);

        MF_ThanhChucNangDanhMucThuoc_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        MF_Them_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_Them_JButton.setText("Thêm");
        MF_Them_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_Them_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_Them_JButton);

        MF_Xoa_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_Xoa_JButton.setText("Xóa");
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_Xoa_JButton);

        MF_TraCuu_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_TraCuu_JButton.setText("Tra cứu");
        MF_TraCuu_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_TraCuu_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_TraCuu_JButton);

        MF_TraCuu_JTextField.setPreferredSize(new java.awt.Dimension(350, 29));
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_TraCuu_JTextField);

        MF_XuatDanhMuc_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_XuatDanhMuc_JButton.setText("Xuất danh mục");
        MF_XuatDanhMuc_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_XuatDanhMuc_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_XuatDanhMuc_JButton);

        MF_NhapDanhMuc_JButton.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_NhapDanhMuc_JButton.setText("Nhập danh mục");
        MF_NhapDanhMuc_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_NhapDanhMuc_JButtonActionPerformed(evt);
            }
        });
        MF_ThanhChucNangDanhMucThuoc_JPanel.add(MF_NhapDanhMuc_JButton);

        javax.swing.GroupLayout MF_DanhMucThuoc_JPanelLayout = new javax.swing.GroupLayout(MF_DanhMucThuoc_JPanel);
        MF_DanhMucThuoc_JPanel.setLayout(MF_DanhMucThuoc_JPanelLayout);
        MF_DanhMucThuoc_JPanelLayout.setHorizontalGroup(
            MF_DanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_DanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addComponent(MF_ThanhChucNangDanhMucThuoc_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_DanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_NoiDungDanhMucThuoc_JScrollPane)
                .addContainerGap())
        );
        MF_DanhMucThuoc_JPanelLayout.setVerticalGroup(
            MF_DanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_DanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addComponent(MF_NoiDungDanhMucThuoc_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MF_ThanhChucNangDanhMucThuoc_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Danh mục thuốc", MF_DanhMucThuoc_JPanel);

        MF_NoiDungLichSu_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MF_NoiDungLichSu_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        MF_KhungNoiDungLichSu_JPanel.setLayout(new java.awt.GridLayout(1, 1));
        MF_NoiDungLichSu_JScrollPane.setViewportView(MF_KhungNoiDungLichSu_JPanel);

        MF_ThanhChucNangLichSu_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        MF_TraCuuThuocSuDung_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MF_TraCuuThuocSuDung_JLabel.setText("Tra cứu thuốc đã sử dụng:");
        MF_ThanhChucNangLichSu_JPanel.add(MF_TraCuuThuocSuDung_JLabel);

        MF_TraCuuThuocSuDung_JTextField.setPreferredSize(new java.awt.Dimension(250, 26));
        MF_ThanhChucNangLichSu_JPanel.add(MF_TraCuuThuocSuDung_JTextField);

        MF_TraCuuThuocSuDung_JButton.setText("Tra cứu");
        MF_ThanhChucNangLichSu_JPanel.add(MF_TraCuuThuocSuDung_JButton);

        MF_XuatLichSu_JButton.setText("Xuất lịch sử");
        MF_ThanhChucNangLichSu_JPanel.add(MF_XuatLichSu_JButton);

        MF_BaoCaoThoiQuen_JButton.setText("Báo cáo thói quen");
        MF_ThanhChucNangLichSu_JPanel.add(MF_BaoCaoThoiQuen_JButton);

        javax.swing.GroupLayout MF_LichSu_JPanelLayout = new javax.swing.GroupLayout(MF_LichSu_JPanel);
        MF_LichSu_JPanel.setLayout(MF_LichSu_JPanelLayout);
        MF_LichSu_JPanelLayout.setHorizontalGroup(
            MF_LichSu_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_LichSu_JPanelLayout.createSequentialGroup()
                .addComponent(MF_ThanhChucNangLichSu_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_LichSu_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_NoiDungLichSu_JScrollPane)
                .addContainerGap())
        );
        MF_LichSu_JPanelLayout.setVerticalGroup(
            MF_LichSu_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_LichSu_JPanelLayout.createSequentialGroup()
                .addComponent(MF_NoiDungLichSu_JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MF_ThanhChucNangLichSu_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Lịch sử", MF_LichSu_JPanel);

        MF_NoiDungTraCuuOnline_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MF_NoiDungTraCuuOnline_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout MF_KhungNoiDungTraCuuOnline_JPanelLayout = new javax.swing.GroupLayout(MF_KhungNoiDungTraCuuOnline_JPanel);
        MF_KhungNoiDungTraCuuOnline_JPanel.setLayout(MF_KhungNoiDungTraCuuOnline_JPanelLayout);
        MF_KhungNoiDungTraCuuOnline_JPanelLayout.setHorizontalGroup(
            MF_KhungNoiDungTraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1041, Short.MAX_VALUE)
        );
        MF_KhungNoiDungTraCuuOnline_JPanelLayout.setVerticalGroup(
            MF_KhungNoiDungTraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MF_NoiDungTraCuuOnline_JScrollPane.setViewportView(MF_KhungNoiDungTraCuuOnline_JPanel);

        MF_ThanhChucNangTraCuuOnline_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        MF_TenThuoc_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc_JLabel.setText("Tên thuốc:");
        MF_TenThuoc_JLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TenThuoc_JLabel);

        MF_TraCuuOnline_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TraCuuOnline_JTextField.setPreferredSize(new java.awt.Dimension(350, 30));
        MF_TraCuuOnline_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_TraCuuOnline_JTextFieldActionPerformed(evt);
            }
        });
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TraCuuOnline_JTextField);

        MF_TraCuuOnline_JButton.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TraCuuOnline_JButton.setText("Tra cứu");
        MF_TraCuuOnline_JButton.setPreferredSize(new java.awt.Dimension(107, 30));
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TraCuuOnline_JButton);

        javax.swing.GroupLayout MF_TraCuuOnline_JPanelLayout = new javax.swing.GroupLayout(MF_TraCuuOnline_JPanel);
        MF_TraCuuOnline_JPanel.setLayout(MF_TraCuuOnline_JPanelLayout);
        MF_TraCuuOnline_JPanelLayout.setHorizontalGroup(
            MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                        .addComponent(MF_ThanhChucNangTraCuuOnline_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                        .addGroup(MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MF_JSeparator)
                            .addComponent(MF_NoiDungTraCuuOnline_JScrollPane))
                        .addContainerGap())))
        );
        MF_TraCuuOnline_JPanelLayout.setVerticalGroup(
            MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MF_ThanhChucNangTraCuuOnline_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MF_JSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MF_NoiDungTraCuuOnline_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Tra cứu trực tuyến", MF_TraCuuOnline_JPanel);

        MF_KhungNoiDungKiemTraTuongTacThuoc_JTextArea.setColumns(20);
        MF_KhungNoiDungKiemTraTuongTacThuoc_JTextArea.setRows(5);
        MF_NoiDungKiemTraTuongTacThuoc_JScrollPane.setViewportView(MF_KhungNoiDungKiemTraTuongTacThuoc_JTextArea);

        MF_TenThuoc1_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc1_JLabel.setText("Tên thuốc 1:");
        MF_TenThuoc1_JLabel.setPreferredSize(new java.awt.Dimension(132, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane.add(MF_TenThuoc1_JLabel);

        MF_TenThuoc1_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc1_JTextField.setPreferredSize(new java.awt.Dimension(350, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane.add(MF_TenThuoc1_JTextField);

        MF_KiemTra_JButton.setText("Kiểm tra");
        MF_KiemTra_JButton.setPreferredSize(new java.awt.Dimension(110, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane.add(MF_KiemTra_JButton);

        MF_TenThuoc2_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc2_JLabel.setText("Tên thuốc 2:");
        MF_TenThuoc2_JLabel.setPreferredSize(new java.awt.Dimension(132, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane.add(MF_TenThuoc2_JLabel);

        MF_TenThuoc2_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc2_JTextField.setPreferredSize(new java.awt.Dimension(350, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane.add(MF_TenThuoc2_JTextField);

        MF_XoaTatCa_JButton.setText("Xóa");
        MF_XoaTatCa_JButton.setPreferredSize(new java.awt.Dimension(72, 30));
        MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane.add(MF_XoaTatCa_JButton);

        javax.swing.GroupLayout MF_KiemTraTuongTacThuoc_JPanelLayout = new javax.swing.GroupLayout(MF_KiemTraTuongTacThuoc_JPanel);
        MF_KiemTraTuongTacThuoc_JPanel.setLayout(MF_KiemTraTuongTacThuoc_JPanelLayout);
        MF_KiemTraTuongTacThuoc_JPanelLayout.setHorizontalGroup(
            MF_KiemTraTuongTacThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_KiemTraTuongTacThuoc_JPanelLayout.createSequentialGroup()
                .addGroup(MF_KiemTraTuongTacThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 453, Short.MAX_VALUE))
            .addGroup(MF_KiemTraTuongTacThuoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_NoiDungKiemTraTuongTacThuoc_JScrollPane)
                .addContainerGap())
        );
        MF_KiemTraTuongTacThuoc_JPanelLayout.setVerticalGroup(
            MF_KiemTraTuongTacThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_KiemTraTuongTacThuoc_JPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MF_NoiDungKiemTraTuongTacThuoc_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Kiểm tra tương tác thuốc", MF_KiemTraTuongTacThuoc_JPanel);

        MF_Chon_JMenuBar.setBackground(null);
        MF_Chon_JMenuBar.setForeground(null);
        MF_Chon_JMenuBar.setBorderPainted(false);

        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.setText("Chọn");

        MF_CaiDat_JMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_COMMA, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MF_CaiDat_JMenuItem.setText("Cài đặt");
        MF_CaiDat_JMenuItem.setToolTipText("");
        MF_CaiDat_JMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_CaiDat_JMenuItemActionPerformed(evt);
            }
        });
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.add(MF_CaiDat_JMenuItem);

        MF_VePhanMem_JMenuItem.setText("Về phần mềm");
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.add(MF_VePhanMem_JMenuItem);

        MF_VeCaNhan_JMenuItem.setText("Về cá nhân");
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.add(MF_VeCaNhan_JMenuItem);

        MF_Thoat_JMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MF_Thoat_JMenuItem.setText("Thoát");
        MF_Thoat_JMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_Thoat_JMenuItemActionPerformed(evt);
            }
        });
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.add(MF_Thoat_JMenuItem);

        MF_Chon_JMenuBar.add(MF_CaiDat_VePhanMem_Thoat_JMI_JMenu);

        setJMenuBar(MF_Chon_JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MF_IntermidiateContainer_JTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_IntermidiateContainer_JTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MF_Thoat_JMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_Thoat_JMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MF_Thoat_JMenuItemActionPerformed

    private void MF_CaiDat_JMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_CaiDat_JMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_CaiDat_JMenuItemActionPerformed

    private void MF_BoQua_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_BoQua_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_BoQua_JButtonActionPerformed

    private void MF_SuDung1Lan_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_SuDung1Lan_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_SuDung1Lan_JButtonActionPerformed

    private void MF_XuatDanhMuc_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_XuatDanhMuc_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_XuatDanhMuc_JButtonActionPerformed

    private void MF_TraCuu_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_TraCuu_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_TraCuu_JButtonActionPerformed

    private void MF_TraCuuOnline_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_TraCuuOnline_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_TraCuuOnline_JTextFieldActionPerformed

    private void MF_Them_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_Them_JButtonActionPerformed
        // TODO add your handling code here:
        AddMedicationFrame AMF = new AddMedicationFrame();
    }//GEN-LAST:event_MF_Them_JButtonActionPerformed

    private void MF_NhapDanhMuc_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_NhapDanhMuc_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_NhapDanhMuc_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MF_BaoCaoThoiQuen_JButton;
    private javax.swing.JButton MF_BoQua_JButton;
    private javax.swing.JMenuItem MF_CaiDat_JMenuItem;
    private javax.swing.JMenu MF_CaiDat_VePhanMem_Thoat_JMI_JMenu;
    private javax.swing.JMenuBar MF_Chon_JMenuBar;
    private javax.swing.JPanel MF_DanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_HomNay_JPanel;
    private javax.swing.JTabbedPane MF_IntermidiateContainer_JTabbedPane;
    private javax.swing.JSeparator MF_JSeparator;
    private javax.swing.JPanel MF_KhungNoiDungDanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_KhungNoiDungHomNay_JPanel;
    private javax.swing.JTextArea MF_KhungNoiDungKiemTraTuongTacThuoc_JTextArea;
    private javax.swing.JPanel MF_KhungNoiDungLichSu_JPanel;
    private javax.swing.JPanel MF_KhungNoiDungTraCuuOnline_JPanel;
    private javax.swing.JPanel MF_KiemTraTuongTacThuoc_JPanel;
    private javax.swing.JButton MF_KiemTra_JButton;
    private javax.swing.JPanel MF_LichSu_JPanel;
    private javax.swing.JButton MF_NhapDanhMuc_JButton;
    private javax.swing.JScrollPane MF_NoiDungDanhMucThuoc_JScrollPane;
    private javax.swing.JScrollPane MF_NoiDungHomNay_JScrollPane;
    private javax.swing.JScrollPane MF_NoiDungKiemTraTuongTacThuoc_JScrollPane;
    private javax.swing.JScrollPane MF_NoiDungLichSu_JScrollPane;
    private javax.swing.JScrollPane MF_NoiDungTraCuuOnline_JScrollPane;
    private javax.swing.JButton MF_SuDung1Lan_JButton;
    private javax.swing.JLabel MF_TenThuoc1_JLabel;
    private javax.swing.JTextField MF_TenThuoc1_JTextField;
    private javax.swing.JLabel MF_TenThuoc2_JLabel;
    private javax.swing.JTextField MF_TenThuoc2_JTextField;
    private javax.swing.JLabel MF_TenThuoc_JLabel;
    private javax.swing.JPanel MF_ThanhChucNangDanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_ThanhChucNangHomNay_JPanel;
    private javax.swing.JPanel MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPane2_JPane;
    private javax.swing.JPanel MF_ThanhChucNangKiemTraTuongTacThuoc_1_JPanel_JPane;
    private javax.swing.JPanel MF_ThanhChucNangLichSu_JPanel;
    private javax.swing.JPanel MF_ThanhChucNangTraCuuOnline_JPanel;
    private javax.swing.JButton MF_Them_JButton;
    private javax.swing.JMenuItem MF_Thoat_JMenuItem;
    private javax.swing.JButton MF_TraCuuOnline_JButton;
    private javax.swing.JPanel MF_TraCuuOnline_JPanel;
    private javax.swing.JTextField MF_TraCuuOnline_JTextField;
    private javax.swing.JButton MF_TraCuuThuocSuDung_JButton;
    private javax.swing.JLabel MF_TraCuuThuocSuDung_JLabel;
    private javax.swing.JTextField MF_TraCuuThuocSuDung_JTextField;
    private javax.swing.JButton MF_TraCuu_JButton;
    private javax.swing.JTextField MF_TraCuu_JTextField;
    private javax.swing.JMenuItem MF_VeCaNhan_JMenuItem;
    private javax.swing.JMenuItem MF_VePhanMem_JMenuItem;
    private javax.swing.JButton MF_XacNhan_JButton;
    private javax.swing.JButton MF_XoaTatCa_JButton;
    private javax.swing.JButton MF_Xoa_JButton;
    private javax.swing.JButton MF_XuatDanhMuc_JButton;
    private javax.swing.JButton MF_XuatLichSu_JButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
