/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userview;

/**
 *
 * @author shanghuang
 */
public class SpecificFrequencyUsageInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form SpecificFrequencyUsageInformationFrame
     */
    public SpecificFrequencyUsageInformationFrame() {
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMedicationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
    }
    
    public void addDayOfWeekPanel() {
        this.add(this.SFUIF_SpecificDayOfWeekInformation_JPanel);
        this.setSize(this.SFUIF_SpecificDayOfWeekInformation_JPanel.getSize());
    }
    
    public void addDayOfMonthPanel() {
        this.add(this.SFUIF_SpecificDayOfMonthInformation_JPanel);
        this.setSize(this.SFUIF_SpecificDayOfMonthInformation_JPanel.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SFUIF_SpecificDayOfWeekInformation_JPanel = new javax.swing.JPanel();
        SFUIF_DayOfWeek_JPanel = new javax.swing.JPanel();
        T2 = new javax.swing.JToggleButton();
        T3 = new javax.swing.JToggleButton();
        T4 = new javax.swing.JToggleButton();
        T5 = new javax.swing.JToggleButton();
        T6 = new javax.swing.JToggleButton();
        T7 = new javax.swing.JToggleButton();
        CN = new javax.swing.JToggleButton();
        SFUIF_OK_JButton = new javax.swing.JButton();
        SFUIF_SpecificDayOfMonthInformation_JPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        T2.setText("T2");

        T3.setText("T3");

        T4.setText("T4");

        T5.setText("T5");

        T6.setText("T6");

        T7.setText("T7");

        CN.setText("CN");

        javax.swing.GroupLayout SFUIF_DayOfWeek_JPanelLayout = new javax.swing.GroupLayout(SFUIF_DayOfWeek_JPanel);
        SFUIF_DayOfWeek_JPanel.setLayout(SFUIF_DayOfWeek_JPanelLayout);
        SFUIF_DayOfWeek_JPanelLayout.setHorizontalGroup(
            SFUIF_DayOfWeek_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SFUIF_DayOfWeek_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(T2)
                .addGap(5, 5, 5)
                .addComponent(T3)
                .addGap(5, 5, 5)
                .addComponent(T4)
                .addGap(5, 5, 5)
                .addComponent(T5)
                .addGap(5, 5, 5)
                .addComponent(T6)
                .addGap(5, 5, 5)
                .addComponent(T7)
                .addGap(5, 5, 5)
                .addComponent(CN)
                .addContainerGap())
        );
        SFUIF_DayOfWeek_JPanelLayout.setVerticalGroup(
            SFUIF_DayOfWeek_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SFUIF_DayOfWeek_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SFUIF_DayOfWeek_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(T2)
                    .addComponent(T3)
                    .addComponent(T4)
                    .addComponent(T5)
                    .addComponent(T6)
                    .addComponent(T7)
                    .addComponent(CN))
                .addContainerGap())
        );

        SFUIF_OK_JButton.setText("OK");

        javax.swing.GroupLayout SFUIF_SpecificDayOfWeekInformation_JPanelLayout = new javax.swing.GroupLayout(SFUIF_SpecificDayOfWeekInformation_JPanel);
        SFUIF_SpecificDayOfWeekInformation_JPanel.setLayout(SFUIF_SpecificDayOfWeekInformation_JPanelLayout);
        SFUIF_SpecificDayOfWeekInformation_JPanelLayout.setHorizontalGroup(
            SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SFUIF_DayOfWeek_JPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createSequentialGroup()
                        .addComponent(SFUIF_OK_JButton)
                        .addContainerGap())))
        );
        SFUIF_SpecificDayOfWeekInformation_JPanelLayout.setVerticalGroup(
            SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SFUIF_SpecificDayOfWeekInformation_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SFUIF_DayOfWeek_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SFUIF_OK_JButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SFUIF_SpecificDayOfMonthInformation_JPanel.add(jTextField1);

        jButton1.setText("+");
        SFUIF_SpecificDayOfMonthInformation_JPanel.add(jButton1);

        jButton2.setText("-");
        SFUIF_SpecificDayOfMonthInformation_JPanel.add(jButton2);

        jButton3.setText("OK");
        SFUIF_SpecificDayOfMonthInformation_JPanel.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecificFrequencyUsageInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecificFrequencyUsageInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecificFrequencyUsageInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecificFrequencyUsageInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecificFrequencyUsageInformationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton CN;
    private javax.swing.JPanel SFUIF_DayOfWeek_JPanel;
    private javax.swing.JButton SFUIF_OK_JButton;
    private javax.swing.JPanel SFUIF_SpecificDayOfMonthInformation_JPanel;
    private javax.swing.JPanel SFUIF_SpecificDayOfWeekInformation_JPanel;
    private javax.swing.JToggleButton T2;
    private javax.swing.JToggleButton T3;
    private javax.swing.JToggleButton T4;
    private javax.swing.JToggleButton T5;
    private javax.swing.JToggleButton T6;
    private javax.swing.JToggleButton T7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
