CREATE TABLE CANHAN (
    USERNAME VARCHAR(10) NOT NULL,
    MATKHAU VARCHAR(10) NOT NULL,
    HOTEN NVARCHAR2(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL, 
    TUOI INTEGER NOT NULL,
    KVSONG NVARCHAR2(20) NOT NULL,
    TIENSUBENHLY NVARCHAR2(2000),
    CONSTRAINT PK_ID_CANHAN PRIMARY KEY (USERNAME)
);

CREATE TABLE HOSOTHUOC (
    IDEN_HST VARCHAR(10) NOT NULL,
    NGAYLAP DATE NOT NULL,
    USERNAME VARCHAR(10) NOT NULL,
    DUONGDANDANHSACHTHUOC VARCHAR(200),
    CONSTRAINT PK_IDHST_HOSOTHUOC PRIMARY KEY (IDEN_HST),
    CONSTRAINT FK_ID_HOSOTHUOC FOREIGN KEY (USERNAME) REFERENCES CANHAN(USERNAME)
);

CREATE TABLE CAIDATTHAMSO (
    USERNAME VARCHAR(10) NOT NULL,
    DUONGDANCAIDAT VARCHAR(200),
    CONSTRAINT PK_ID_CAIDATTHAMSO PRIMARY KEY (USERNAME),
    CONSTRAINT FK_ID_CAIDATTHAMSO FOREIGN KEY (USERNAME) REFERENCES CANHAN(USERNAME)
);

CREATE TABLE LICHSUTHUOC (
    USERNAME VARCHAR(10) NOT NULL,
    DUONGDANLICHSU VARCHAR(200),
    TONGKETTHOIQUEN VARCHAR(100),
    CONSTRAINT PK_ID_LICHSUTHUOC PRIMARY KEY (USERNAME),
    CONSTRAINT FK_ID_LICHSUTHUOC FOREIGN KEY (USERNAME) REFERENCES CANHAN(USERNAME)
);

CREATE TABLE PHANHOI (
    IDEN_PH VARCHAR(10) NOT NULL,
    NGAYGHINHAN DATE NOT NULL,
    USERNAME VARCHAR(10) NOT NULL,
    NOIDUNG VARCHAR(100),
    CONSTRAINT PK_IDPH_PHANHOI PRIMARY KEY (IDEN_PH),
    CONSTRAINT FK_ID_PHANHOI FOREIGN KEY (USERNAME) REFERENCES CANHAN(USERNAME)
);

--DROP TABLE HOSOTHUOC;
--DROP TABLE CAIDATTHAMSO;
--DROP TABLE LICHSUTHUOC;
--DROP TABLE PHANHOI;
DROP TABLE CANHAN;

ALTER TABLE CANHAN ADD CONSTRAINT PK_USERNAME PRIMARY KEY (IDEN, USERNAME);

INSERT INTO CANHAN(USERNAME, MATKHAU, HOTEN, EMAIL, TUOI, KVSONG, TIENSUBENHLY) VALUES ('HuynhThanh', '181105', 'Huynh Thanh Sang', 'macsin233@gmail.com', 20, 'Tien Giang', 'Khong co');
INSERT INTO CANHAN(USERNAME, MATKHAU, HOTEN, EMAIL, TUOI, KVSONG, TIENSUBENHLY) VALUES ('Hts101105', '181105', 'Huynh Trong Tuyen', 'ignisolomon111@gmail.com', 20, 'Binh Duong', 'Khong co');

SELECT CANHAN.USERNAME, CANHAN.EMAIL FROM CANHAN WHERE CANHAN.USERNAME = 'HuynhThanh';

DELETE FROM CANHAN WHERE CANHAN.USERNAME='tnkl123456';

SELECT * FROM CANHAN WHERE CANHAN.USERNAME = '1234' AND CANHAN.MATKHAU = '45667';

UPDATE CANHAN SET CANHAN.MATKHAU = '123456' WHERE CANHAN.USERNAME = 'HuynhThanh' AND CANHAN.EMAIL = 'macsin233@gmail.com';