/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elementpanel;

import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;
import object.MedicineObject;
import userview.EditMedicationFrame;

/**
 *
 * @author shanghuang
 */
public class MedicineItemPanel extends javax.swing.JPanel {
	private MedicineObject mo;
	/**
	 * Creates new form MedicineItemPanel
	 */
	public MedicineItemPanel() {
		FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MIP_TenThuoc_JLabel = new javax.swing.JLabel();
        MIP_Info_JPanel = new javax.swing.JPanel();
        MIP_Left_JPanel = new javax.swing.JPanel();
        MIP_DViThuoc_JLabel = new javax.swing.JLabel();
        MIP_GCThuoc_JLabel = new javax.swing.JLabel();
        MIP_UuTien_JLabel = new javax.swing.JLabel();
        MIP_SL_JLabel = new javax.swing.JLabel();
        MIP_Right_JPanel = new javax.swing.JPanel();
        MIP_Edit_JButton = new javax.swing.JButton();
        MIP_Duplicate_JButton = new javax.swing.JButton();
        MIP_Delete_JButton = new javax.swing.JButton();
        MIP_Refill_JButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        setMaximumSize(new java.awt.Dimension(1041, 90));
        setMinimumSize(new java.awt.Dimension(1041, 90));
        setPreferredSize(new java.awt.Dimension(1041, 90));
        setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        MIP_TenThuoc_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 24)); // NOI18N
        MIP_TenThuoc_JLabel.setText("TenThuoc");
        MIP_TenThuoc_JLabel.setMaximumSize(new java.awt.Dimension(1029, 54));
        MIP_TenThuoc_JLabel.setMinimumSize(new java.awt.Dimension(1029, 54));
        MIP_TenThuoc_JLabel.setPreferredSize(new java.awt.Dimension(1029, 54));
        add(MIP_TenThuoc_JLabel);

        MIP_Info_JPanel.setMaximumSize(new java.awt.Dimension(1029, 54));
        MIP_Info_JPanel.setMinimumSize(new java.awt.Dimension(1029, 54));
        MIP_Info_JPanel.setPreferredSize(new java.awt.Dimension(1029, 54));
        MIP_Info_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        MIP_Left_JPanel.setMaximumSize(new java.awt.Dimension(750, 40));
        MIP_Left_JPanel.setMinimumSize(new java.awt.Dimension(750, 40));
        MIP_Left_JPanel.setPreferredSize(new java.awt.Dimension(750, 40));
        MIP_Left_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        MIP_DViThuoc_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MIP_DViThuoc_JLabel.setText("DonViThuoc");
        MIP_DViThuoc_JLabel.setMaximumSize(new java.awt.Dimension(150, 30));
        MIP_DViThuoc_JLabel.setMinimumSize(new java.awt.Dimension(150, 30));
        MIP_DViThuoc_JLabel.setPreferredSize(new java.awt.Dimension(150, 30));
        MIP_Left_JPanel.add(MIP_DViThuoc_JLabel);

        MIP_GCThuoc_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MIP_GCThuoc_JLabel.setText("GhiChuThuoc");
        MIP_GCThuoc_JLabel.setMaximumSize(new java.awt.Dimension(300, 30));
        MIP_GCThuoc_JLabel.setMinimumSize(new java.awt.Dimension(300, 30));
        MIP_GCThuoc_JLabel.setPreferredSize(new java.awt.Dimension(300, 30));
        MIP_Left_JPanel.add(MIP_GCThuoc_JLabel);

        MIP_UuTien_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MIP_UuTien_JLabel.setText("UuTien");
        MIP_UuTien_JLabel.setMaximumSize(new java.awt.Dimension(180, 30));
        MIP_UuTien_JLabel.setMinimumSize(new java.awt.Dimension(180, 30));
        MIP_UuTien_JLabel.setPreferredSize(new java.awt.Dimension(180, 30));
        MIP_Left_JPanel.add(MIP_UuTien_JLabel);

        MIP_SL_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 18)); // NOI18N
        MIP_SL_JLabel.setText("SL");
        MIP_SL_JLabel.setMaximumSize(new java.awt.Dimension(90, 30));
        MIP_SL_JLabel.setMinimumSize(new java.awt.Dimension(90, 30));
        MIP_SL_JLabel.setPreferredSize(new java.awt.Dimension(90, 30));
        MIP_Left_JPanel.add(MIP_SL_JLabel);

        MIP_Info_JPanel.add(MIP_Left_JPanel);

        MIP_Right_JPanel.setMaximumSize(new java.awt.Dimension(186, 42));
        MIP_Right_JPanel.setMinimumSize(new java.awt.Dimension(186, 42));
        MIP_Right_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        MIP_Edit_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        MIP_Edit_JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        MIP_Edit_JButton.setMinimumSize(new java.awt.Dimension(40, 40));
        MIP_Edit_JButton.setPreferredSize(new java.awt.Dimension(40, 40));
        MIP_Edit_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIP_Edit_JButtonActionPerformed(evt);
            }
        });
        MIP_Right_JPanel.add(MIP_Edit_JButton);

        MIP_Duplicate_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/duplicate.png"))); // NOI18N
        MIP_Duplicate_JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        MIP_Duplicate_JButton.setMinimumSize(new java.awt.Dimension(40, 40));
        MIP_Duplicate_JButton.setPreferredSize(new java.awt.Dimension(40, 40));
        MIP_Duplicate_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIP_Duplicate_JButtonActionPerformed(evt);
            }
        });
        MIP_Right_JPanel.add(MIP_Duplicate_JButton);

        MIP_Delete_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        MIP_Delete_JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        MIP_Delete_JButton.setMinimumSize(new java.awt.Dimension(40, 40));
        MIP_Delete_JButton.setPreferredSize(new java.awt.Dimension(40, 40));
        MIP_Delete_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIP_Delete_JButtonActionPerformed(evt);
            }
        });
        MIP_Right_JPanel.add(MIP_Delete_JButton);

        MIP_Refill_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refill.png"))); // NOI18N
        MIP_Refill_JButton.setMaximumSize(new java.awt.Dimension(40, 40));
        MIP_Refill_JButton.setMinimumSize(new java.awt.Dimension(40, 40));
        MIP_Refill_JButton.setPreferredSize(new java.awt.Dimension(40, 40));
        MIP_Refill_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIP_Refill_JButtonActionPerformed(evt);
            }
        });
        MIP_Right_JPanel.add(MIP_Refill_JButton);

        MIP_Info_JPanel.add(MIP_Right_JPanel);

        add(MIP_Info_JPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void MIP_Edit_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIP_Edit_JButtonActionPerformed
        // TODO add your handling code here:
		EditMedicationFrame emf = new EditMedicationFrame(MedicineItemPanel.this);
    }//GEN-LAST:event_MIP_Edit_JButtonActionPerformed

    private void MIP_Duplicate_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIP_Duplicate_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIP_Duplicate_JButtonActionPerformed

    private void MIP_Delete_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIP_Delete_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIP_Delete_JButtonActionPerformed

    private void MIP_Refill_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIP_Refill_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIP_Refill_JButtonActionPerformed

	public void loadData(
		MedicineObject mo
	) {
		this.mo = mo;
		MIP_TenThuoc_JLabel.setText(mo.getTenThuoc());
		MIP_DViThuoc_JLabel.setText(mo.getDonVi());
		
		MIP_GCThuoc_JLabel.setText(mo.getGhiChu());
		if (mo.isUuTienThongBao() == true) {
			MIP_UuTien_JLabel.setText("High priority");
		} else {
			MIP_UuTien_JLabel.setText("Low priority");
		}

		MIP_SL_JLabel.setText(String.valueOf(mo.getSLHienCo()));
	}
	
	public MedicineObject getMedicineObject() {
		return this.mo;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MIP_DViThuoc_JLabel;
    private javax.swing.JButton MIP_Delete_JButton;
    private javax.swing.JButton MIP_Duplicate_JButton;
    private javax.swing.JButton MIP_Edit_JButton;
    private javax.swing.JLabel MIP_GCThuoc_JLabel;
    private javax.swing.JPanel MIP_Info_JPanel;
    private javax.swing.JPanel MIP_Left_JPanel;
    private javax.swing.JButton MIP_Refill_JButton;
    private javax.swing.JPanel MIP_Right_JPanel;
    private javax.swing.JLabel MIP_SL_JLabel;
    private javax.swing.JLabel MIP_TenThuoc_JLabel;
    private javax.swing.JLabel MIP_UuTien_JLabel;
    // End of variables declaration//GEN-END:variables
}
