-- QUES 1
-- CREATE TABLE USER (
-- 	USERNAME VARCHAR(10), 
--  PASSWORD VARCHAR(20),
--  PRIMARY KEY (USERNAME)
-- );
-- INSERT INTO USER VALUE (?,?);
-- SELECT * FROM USER WHERE USERNAME = ? AND PASSWORD = ?

-- QUES 2
-- CREATE TABLE BACSI (
-- 	MABS CHAR(4),
--     TENBS VARCHAR(20),
--     PRIMARY KEY (MABS)
-- );
-- CREATE TABLE BENHNHAN (
-- 	MABN CHAR(4),
--     TENBN VARCHAR(20),
--     NGSINH DATE,
--     DCHI VARCHAR(50),
--     DTHOAI VARCHAR(10),
--     GIOITINH BOOLEAN,
--     PRIMARY KEY (MABN)
-- );
-- CREATE TABLE DICHVU (
-- 	MADV CHAR(6),
--     TENDV VARCHAR(20),
--     DONGIA BIGINT,
--     PRIMARY KEY (MADV)
-- );
-- CREATE TABLE KHAMBENH (
-- 	   MAKB CHAR(6),
--     MABN CHAR(4),
--     MABS CHAR(4),
--     NGAYKHAM DATE,
--     YEUCAUKHAM VARCHAR(50),
--     KETLUAN VARCHAR(10),
--     THANHTOAN BOOLEAN,
--     PRIMARY KEY (MAKB),
--     FOREIGN KEY (MABN) REFERENCES BENHNHAN(MABN),
--     FOREIGN KEY (MABS) REFERENCES BACSI(MABS)
-- );
-- CREATE TABLE THUPHI (
-- 	MAKB CHAR(6),
--     MADV CHAR(6),
--     SOLUONG INT,
--     THANHTIEN BIGINT,
--     PRIMARY KEY (MAKB, MADV),
--     FOREIGN KEY (MAKB) REFERENCES KHAMBENH(MAKB),
--     FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)
-- );
SELECT BACSI.TENBS FROM BACSI;
-- INSERT INTO BENHNHAN VALUE ("A1", "SANG", "2005-11-18", "10/2a", "0765631367", true);
DELETE FROM BENHNHAN WHERE BENHNHAN.MABN = "1811";

SELECT BACSI.MABS FROM BACSI WHERE BACSI.TENBS = "Nguyen Van A";

INSERT INTO BACSI VALUE ("BS01", "Nguyen Van A");
INSERT INTO BACSI VALUE ("BS02", "Le Thi B");
INSERT INTO BACSI VALUE ("BS03", "Tran Tong C");
INSERT INTO BACSI VALUE ("BS04", "Huynh Nguyen D");

SELECT * FROM KHAMBENH;
DELETE FROM KHAMBENH WHERE MABN = "BN01";

SELECT BENHNHAN.TENBN
FROM KHAMBENH 
JOIN BENHNHAN
	ON KHAMBENH.MABN = BENHNHAN.MABN
JOIN BACSI
	ON KHAMBENH.MABS = BACSI.MABS
WHERE BACSI.TENBS = "Nguyen Van A";
