package view_ques2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 *
 *  author: CacAnhDaDen (nbzzz, Hinno, _qnk_)
 *
 */

public class AddInfoFrame extends javax.swing.JFrame {
    private MainFrame mf;
    int DEBUG = 1;
    /**
     * Creates new form AddInfoFrame
     */
    public AddInfoFrame(MainFrame mf) {
        this.mf = mf;
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setFrameInCenter();
        this.setVisible(true);
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperLevel = new javax.swing.JPanel();
        MaBNPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MaBNInput = new javax.swing.JTextField();
        TenBNPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TenBNInput = new javax.swing.JTextField();
        NgSinhPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NgSinhInput = new com.toedter.calendar.JDateChooser();
        DChiPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DChiInput = new javax.swing.JTextField();
        DThoaiPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        DThoaiInput = new javax.swing.JTextField();
        GTinhPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        GTinhInput = new javax.swing.JComboBox<>();
        LowerLevel = new javax.swing.JPanel();
        ThemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpperLevel.setLayout(new java.awt.GridLayout(6, 1, 0, 5));

        jLabel1.setText("Mã bệnh nhân");
        jLabel1.setPreferredSize(new java.awt.Dimension(140, 20));

        MaBNInput.setText("Mã bệnh nhân");
        MaBNInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout MaBNPanelLayout = new javax.swing.GroupLayout(MaBNPanel);
        MaBNPanel.setLayout(MaBNPanelLayout);
        MaBNPanelLayout.setHorizontalGroup(
            MaBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaBNPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MaBNInput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MaBNPanelLayout.setVerticalGroup(
            MaBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaBNPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MaBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MaBNInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        UpperLevel.add(MaBNPanel);

        jLabel2.setText("Tên bệnh nhân");
        jLabel2.setPreferredSize(new java.awt.Dimension(140, 20));

        TenBNInput.setText("Tên bệnh nhân");
        TenBNInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout TenBNPanelLayout = new javax.swing.GroupLayout(TenBNPanel);
        TenBNPanel.setLayout(TenBNPanelLayout);
        TenBNPanelLayout.setHorizontalGroup(
            TenBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TenBNPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TenBNInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TenBNPanelLayout.setVerticalGroup(
            TenBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TenBNPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TenBNPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TenBNInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        UpperLevel.add(TenBNPanel);

        jLabel3.setText("Ngày sinh");
        jLabel3.setPreferredSize(new java.awt.Dimension(140, 20));

        NgSinhInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout NgSinhPanelLayout = new javax.swing.GroupLayout(NgSinhPanel);
        NgSinhPanel.setLayout(NgSinhPanelLayout);
        NgSinhPanelLayout.setHorizontalGroup(
            NgSinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgSinhPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NgSinhInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        NgSinhPanelLayout.setVerticalGroup(
            NgSinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NgSinhPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NgSinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NgSinhInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        UpperLevel.add(NgSinhPanel);

        jLabel4.setText("Địa chỉ");
        jLabel4.setPreferredSize(new java.awt.Dimension(140, 20));

        DChiInput.setText("Địa chỉ");
        DChiInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout DChiPanelLayout = new javax.swing.GroupLayout(DChiPanel);
        DChiPanel.setLayout(DChiPanelLayout);
        DChiPanelLayout.setHorizontalGroup(
            DChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DChiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DChiInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DChiPanelLayout.setVerticalGroup(
            DChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DChiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DChiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DChiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        UpperLevel.add(DChiPanel);

        jLabel5.setText("Điện thoại");
        jLabel5.setPreferredSize(new java.awt.Dimension(140, 20));

        DThoaiInput.setText("Điện thoại");
        DThoaiInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout DThoaiPanelLayout = new javax.swing.GroupLayout(DThoaiPanel);
        DThoaiPanel.setLayout(DThoaiPanelLayout);
        DThoaiPanelLayout.setHorizontalGroup(
            DThoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DThoaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DThoaiInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DThoaiPanelLayout.setVerticalGroup(
            DThoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DThoaiPanelLayout.createSequentialGroup()
                .addGroup(DThoaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DThoaiPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DThoaiInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );

        UpperLevel.add(DThoaiPanel);

        jLabel6.setText("Giới tính");
        jLabel6.setPreferredSize(new java.awt.Dimension(140, 20));

        GTinhInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        GTinhInput.setPreferredSize(new java.awt.Dimension(268, 20));

        javax.swing.GroupLayout GTinhPanelLayout = new javax.swing.GroupLayout(GTinhPanel);
        GTinhPanel.setLayout(GTinhPanelLayout);
        GTinhPanelLayout.setHorizontalGroup(
            GTinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GTinhPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GTinhInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GTinhPanelLayout.setVerticalGroup(
            GTinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GTinhPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GTinhPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GTinhInput, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        UpperLevel.add(GTinhPanel);

        ThemButton.setText("Thêm");
        ThemButton.setPreferredSize(new java.awt.Dimension(110, 50));
        ThemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemButtonActionPerformed(evt);
            }
        });
        LowerLevel.add(ThemButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpperLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LowerLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpperLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LowerLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Connection connect() {
        // Connection parameter
        String dbURL = "jdbc:mysql://localhost:3306/QLKB";
        String driver = "com.mysql.jdbc.Driver";
        Connection con = null;
        
        // Catching error in connection
        try {
            // Class loader
            Class.forName(driver);
            
            // Connection
            con = DriverManager.getConnection(dbURL, "root", "181105");

            // Debug 
            if (con != null) {
                if (DEBUG == 1) {
                    System.out.println("Kết nối đến cơ sử dữ liệu thành công");
                }
            }
        } catch(SQLException se) { 
            // SQL Exception
            System.out.println(se.getMessage());
        } catch (ClassNotFoundException ex) { 
            // Class Exception
            Logger.getLogger(AddInfoFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Return connection
        if (con != null) {
            return con;
        } else {
            return null;
        }
    }    
    
    private void ThemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemButtonActionPerformed
        NgSinhInput.setDateFormatString("y-M-d");
        Date temp = NgSinhInput.getDate();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        BenhNhan bn = new BenhNhan(
                MaBNInput.getText(),
                TenBNInput.getText(),
                formatter.format(temp),
                DChiInput.getText(),
                DThoaiInput.getText(),
                GTinhInput.getSelectedItem().toString()
        );
        
        if (DEBUG == 1) {
            bn.print();
        }
        
        // Create connection
        Connection con = connect();

        if (con == null) {
            // Debug
            if (DEBUG == 1) {
                System.out.println("Không thể kết nối đến cơ sử dữ liệu");
            }   
        } else {
            // Query
            boolean result = false;
            String query = "INSERT INTO BENHNHAN VALUE (?, ?, ?, ?, ?, ?)";

            // Catching error in query execution
            try {
                // Load parameter in to query
                PreparedStatement ps = con.prepareStatement(query);
                ps.setString(1, bn.getInfo(1));
                ps.setString(2, bn.getInfo(2));
                ps.setString(3, bn.getInfo(3));
                ps.setString(4, bn.getInfo(4));
                ps.setString(5, bn.getInfo(5));
                
                if (bn.getInfo(6).contentEquals("Nam") == true) {
                    ps.setString(6, "1");
                } else {
                    ps.setString(6, "0");
                }

                // Execute and return boolean value
                ps.executeUpdate();
                result = true;
                con.close();
            } catch (SQLException se) {
                // SQL Exception
                System.out.println(se.getMessage());
                se.printStackTrace();
            }

            if (result == false) {
                // Error display
                JOptionPane.showMessageDialog(this, "Thêm bệnh nhân không thành công", "Error", JOptionPane.ERROR_MESSAGE);

                // Debug
                if (DEBUG == 1) {
                    System.out.println("Fail");
                }
            } else {
                // Success display
                JOptionPane.showMessageDialog(this, "Thêm bệnh nhân thành công", "Success", JOptionPane.INFORMATION_MESSAGE);

                // Debug
                if (DEBUG == 1) {
                    System.out.println("Sucess");
                }
            }
        }
        
        this.mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ThemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DChiInput;
    private javax.swing.JPanel DChiPanel;
    private javax.swing.JTextField DThoaiInput;
    private javax.swing.JPanel DThoaiPanel;
    private javax.swing.JComboBox<String> GTinhInput;
    private javax.swing.JPanel GTinhPanel;
    private javax.swing.JPanel LowerLevel;
    private javax.swing.JTextField MaBNInput;
    private javax.swing.JPanel MaBNPanel;
    private com.toedter.calendar.JDateChooser NgSinhInput;
    private javax.swing.JPanel NgSinhPanel;
    private javax.swing.JTextField TenBNInput;
    private javax.swing.JPanel TenBNPanel;
    private javax.swing.JButton ThemButton;
    private javax.swing.JPanel UpperLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
