/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supervisorview;
import userview.*;
import java.awt.*;
/**
 *
 * @author shanghuang
 */
public class MainSupervisorFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainSupervisorFrame() {
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        this.setVisible(true);
        this.setFrameInCenter();
    }
    
    public void setFrameInCenter() {
        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        final Dimension screenSize = toolkit.getScreenSize();
        final int x = (screenSize.width - this.getWidth()) / 2;
        final int y = (screenSize.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jComboBox2 = new javax.swing.JComboBox<>();
        MF_IntermidiateContainer_JTabbedPane = new javax.swing.JTabbedPane();
        MF_HomNay_JPanel = new javax.swing.JPanel();
        MF_KhungNoiDungHomNay_JPanel = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        MF_ThanhChucNangHomNay_JPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        MF_DanhMucThuoc_JPanel = new javax.swing.JPanel();
        MF_KhungNoiDungDanhMucThuoc_JPanel = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        MF_ThanhChucNangDanhMucThuoc_JPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        MF_TraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_JSeparator = new javax.swing.JSeparator();
        MF_NoiDungTraCuuOnline_JScrollPane = new javax.swing.JScrollPane();
        MF_KhungNoiDungTraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_ThanhChucNangTraCuuOnline_JPanel = new javax.swing.JPanel();
        MF_TenThuoc_JLabel = new javax.swing.JLabel();
        MF_TraCuuOnline_JTextField = new javax.swing.JTextField();
        MF_TraCuuOnline_JButton = new javax.swing.JButton();
        MF_Xoa_JButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        MF_Chon_JMenuBar = new javax.swing.JMenuBar();
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu = new javax.swing.JMenu();
        MF_Thoat_JMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý dược phẩm cá nhân");
        setResizable(false);

        jSplitPane2.setDividerLocation(527);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Họ và tên", "Tiêu chí thống kê"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        jSplitPane2.setLeftComponent(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jPanel2);

        javax.swing.GroupLayout MF_KhungNoiDungHomNay_JPanelLayout = new javax.swing.GroupLayout(MF_KhungNoiDungHomNay_JPanel);
        MF_KhungNoiDungHomNay_JPanel.setLayout(MF_KhungNoiDungHomNay_JPanelLayout);
        MF_KhungNoiDungHomNay_JPanelLayout.setHorizontalGroup(
            MF_KhungNoiDungHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_KhungNoiDungHomNay_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2)
                .addContainerGap())
        );
        MF_KhungNoiDungHomNay_JPanelLayout.setVerticalGroup(
            MF_KhungNoiDungHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        jLabel1.setText("Loại biểu đồ:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cột", "Tròn" }));
        jComboBox1.setSelectedIndex(-1);

        jLabel2.setText("Tiêu chí thống kê:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tuổi", "Tiền sử bệnh lý", "Khu vực sinh sống" }));
        jComboBox3.setSelectedIndex(-1);

        jButton1.setText("OK");

        javax.swing.GroupLayout MF_ThanhChucNangHomNay_JPanelLayout = new javax.swing.GroupLayout(MF_ThanhChucNangHomNay_JPanel);
        MF_ThanhChucNangHomNay_JPanel.setLayout(MF_ThanhChucNangHomNay_JPanelLayout);
        MF_ThanhChucNangHomNay_JPanelLayout.setHorizontalGroup(
            MF_ThanhChucNangHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_ThanhChucNangHomNay_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        MF_ThanhChucNangHomNay_JPanelLayout.setVerticalGroup(
            MF_ThanhChucNangHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_ThanhChucNangHomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MF_HomNay_JPanelLayout = new javax.swing.GroupLayout(MF_HomNay_JPanel);
        MF_HomNay_JPanel.setLayout(MF_HomNay_JPanelLayout);
        MF_HomNay_JPanelLayout.setHorizontalGroup(
            MF_HomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MF_KhungNoiDungHomNay_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MF_ThanhChucNangHomNay_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MF_HomNay_JPanelLayout.setVerticalGroup(
            MF_HomNay_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_HomNay_JPanelLayout.createSequentialGroup()
                .addComponent(MF_KhungNoiDungHomNay_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MF_ThanhChucNangHomNay_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Thống kê thông tin người dùng", MF_HomNay_JPanel);

        jSplitPane5.setDividerLocation(527);

        jScrollPane7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Họ và tên", "Thói quen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        jScrollPane7.setViewportView(jPanel5);

        jSplitPane5.setLeftComponent(jScrollPane7);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jSplitPane5.setRightComponent(jPanel6);

        javax.swing.GroupLayout MF_KhungNoiDungDanhMucThuoc_JPanelLayout = new javax.swing.GroupLayout(MF_KhungNoiDungDanhMucThuoc_JPanel);
        MF_KhungNoiDungDanhMucThuoc_JPanel.setLayout(MF_KhungNoiDungDanhMucThuoc_JPanelLayout);
        MF_KhungNoiDungDanhMucThuoc_JPanelLayout.setHorizontalGroup(
            MF_KhungNoiDungDanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_KhungNoiDungDanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1146, Short.MAX_VALUE)
                .addContainerGap())
        );
        MF_KhungNoiDungDanhMucThuoc_JPanelLayout.setVerticalGroup(
            MF_KhungNoiDungDanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel3.setText("Loại biểu đồ:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cột", "Tròn" }));
        jComboBox4.setSelectedIndex(-1);

        jButton2.setText("OK");

        javax.swing.GroupLayout MF_ThanhChucNangDanhMucThuoc_JPanelLayout = new javax.swing.GroupLayout(MF_ThanhChucNangDanhMucThuoc_JPanel);
        MF_ThanhChucNangDanhMucThuoc_JPanel.setLayout(MF_ThanhChucNangDanhMucThuoc_JPanelLayout);
        MF_ThanhChucNangDanhMucThuoc_JPanelLayout.setHorizontalGroup(
            MF_ThanhChucNangDanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_ThanhChucNangDanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        MF_ThanhChucNangDanhMucThuoc_JPanelLayout.setVerticalGroup(
            MF_ThanhChucNangDanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_ThanhChucNangDanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MF_DanhMucThuoc_JPanelLayout = new javax.swing.GroupLayout(MF_DanhMucThuoc_JPanel);
        MF_DanhMucThuoc_JPanel.setLayout(MF_DanhMucThuoc_JPanelLayout);
        MF_DanhMucThuoc_JPanelLayout.setHorizontalGroup(
            MF_DanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MF_KhungNoiDungDanhMucThuoc_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_DanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_ThanhChucNangDanhMucThuoc_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MF_DanhMucThuoc_JPanelLayout.setVerticalGroup(
            MF_DanhMucThuoc_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_DanhMucThuoc_JPanelLayout.createSequentialGroup()
                .addComponent(MF_KhungNoiDungDanhMucThuoc_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MF_ThanhChucNangDanhMucThuoc_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Thống kê thói quen người dùng", MF_DanhMucThuoc_JPanel);

        MF_NoiDungTraCuuOnline_JScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        MF_NoiDungTraCuuOnline_JScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout MF_KhungNoiDungTraCuuOnline_JPanelLayout = new javax.swing.GroupLayout(MF_KhungNoiDungTraCuuOnline_JPanel);
        MF_KhungNoiDungTraCuuOnline_JPanel.setLayout(MF_KhungNoiDungTraCuuOnline_JPanelLayout);
        MF_KhungNoiDungTraCuuOnline_JPanelLayout.setHorizontalGroup(
            MF_KhungNoiDungTraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1134, Short.MAX_VALUE)
        );
        MF_KhungNoiDungTraCuuOnline_JPanelLayout.setVerticalGroup(
            MF_KhungNoiDungTraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MF_NoiDungTraCuuOnline_JScrollPane.setViewportView(MF_KhungNoiDungTraCuuOnline_JPanel);

        MF_ThanhChucNangTraCuuOnline_JPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        MF_TenThuoc_JLabel.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TenThuoc_JLabel.setText("Họ và tên:");
        MF_TenThuoc_JLabel.setPreferredSize(new java.awt.Dimension(110, 30));
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TenThuoc_JLabel);

        MF_TraCuuOnline_JTextField.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TraCuuOnline_JTextField.setPreferredSize(new java.awt.Dimension(350, 30));
        MF_TraCuuOnline_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_TraCuuOnline_JTextFieldActionPerformed(evt);
            }
        });
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TraCuuOnline_JTextField);

        MF_TraCuuOnline_JButton.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_TraCuuOnline_JButton.setText("Tra cứu");
        MF_TraCuuOnline_JButton.setPreferredSize(new java.awt.Dimension(107, 30));
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_TraCuuOnline_JButton);

        MF_Xoa_JButton.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        MF_Xoa_JButton.setText("Xóa");
        MF_Xoa_JButton.setPreferredSize(new java.awt.Dimension(107, 30));
        MF_ThanhChucNangTraCuuOnline_JPanel.add(MF_Xoa_JButton);

        javax.swing.GroupLayout MF_TraCuuOnline_JPanelLayout = new javax.swing.GroupLayout(MF_TraCuuOnline_JPanel);
        MF_TraCuuOnline_JPanel.setLayout(MF_TraCuuOnline_JPanelLayout);
        MF_TraCuuOnline_JPanelLayout.setHorizontalGroup(
            MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MF_ThanhChucNangTraCuuOnline_JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MF_JSeparator)
                    .addComponent(MF_NoiDungTraCuuOnline_JScrollPane))
                .addContainerGap())
        );
        MF_TraCuuOnline_JPanelLayout.setVerticalGroup(
            MF_TraCuuOnline_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MF_TraCuuOnline_JPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(MF_ThanhChucNangTraCuuOnline_JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MF_JSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MF_NoiDungTraCuuOnline_JScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Tra cứu thông tin người dùng", MF_TraCuuOnline_JPanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        MF_IntermidiateContainer_JTabbedPane.addTab("Danh sách phản hồi", jPanel3);

        MF_Chon_JMenuBar.setBackground(null);
        MF_Chon_JMenuBar.setForeground(null);
        MF_Chon_JMenuBar.setBorderPainted(false);

        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.setText("Chọn");

        MF_Thoat_JMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MF_Thoat_JMenuItem.setText("Thoát");
        MF_Thoat_JMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MF_Thoat_JMenuItemActionPerformed(evt);
            }
        });
        MF_CaiDat_VePhanMem_Thoat_JMI_JMenu.add(MF_Thoat_JMenuItem);

        MF_Chon_JMenuBar.add(MF_CaiDat_VePhanMem_Thoat_JMI_JMenu);

        setJMenuBar(MF_Chon_JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MF_IntermidiateContainer_JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MF_IntermidiateContainer_JTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MF_Thoat_JMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_Thoat_JMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MF_Thoat_JMenuItemActionPerformed

    private void MF_TraCuuOnline_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MF_TraCuuOnline_JTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MF_TraCuuOnline_JTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainSupervisorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainSupervisorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MF_CaiDat_VePhanMem_Thoat_JMI_JMenu;
    private javax.swing.JMenuBar MF_Chon_JMenuBar;
    private javax.swing.JPanel MF_DanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_HomNay_JPanel;
    private javax.swing.JTabbedPane MF_IntermidiateContainer_JTabbedPane;
    private javax.swing.JSeparator MF_JSeparator;
    private javax.swing.JPanel MF_KhungNoiDungDanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_KhungNoiDungHomNay_JPanel;
    private javax.swing.JPanel MF_KhungNoiDungTraCuuOnline_JPanel;
    private javax.swing.JScrollPane MF_NoiDungTraCuuOnline_JScrollPane;
    private javax.swing.JLabel MF_TenThuoc_JLabel;
    private javax.swing.JPanel MF_ThanhChucNangDanhMucThuoc_JPanel;
    private javax.swing.JPanel MF_ThanhChucNangHomNay_JPanel;
    private javax.swing.JPanel MF_ThanhChucNangTraCuuOnline_JPanel;
    private javax.swing.JMenuItem MF_Thoat_JMenuItem;
    private javax.swing.JButton MF_TraCuuOnline_JButton;
    private javax.swing.JPanel MF_TraCuuOnline_JPanel;
    private javax.swing.JTextField MF_TraCuuOnline_JTextField;
    private javax.swing.JButton MF_Xoa_JButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
