/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package elementpanel;

import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;

/**
 *
 * @author shanghuang
 */
public class TodayItemPanel extends javax.swing.JPanel {

	/**
	 * Creates new form TodayPanel
	 */
	public TodayItemPanel() {
		FlatIntelliJLaf.setup();
		try {
			UIManager.setLookAndFeel( new FlatIntelliJLaf() );
		} catch( Exception ex ) {
			System.err.println( "Failed to initialize LaF" );
		}
		UIManager.put( "Button.arc", 50 );
		UIManager.put( "Component.arc", 50 );
		UIManager.put( "ProgressBar.arc", 50 );
		UIManager.put( "TextComponent.arc", 50 );
		UIManager.put( "TextArea.border", 50 );
		UIManager.put( "ScrollPane.TextComponent.arc", 50 );
		initComponents();
	}
	
	public void setData(String time) {
		TIP_ThoiGian_JLabel.setText(time);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TIP_UpperPanel_JPanel = new javax.swing.JPanel();
        TIP_ThoiGian_JLabel = new javax.swing.JLabel();
        TIP_JSeperator = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1041, 110));
        setMinimumSize(new java.awt.Dimension(1041, 110));
        setPreferredSize(new java.awt.Dimension(1041, 110));
        setLayout(new java.awt.GridLayout(1, 1));

        TIP_UpperPanel_JPanel.setMaximumSize(new java.awt.Dimension(1029, 70));
        TIP_UpperPanel_JPanel.setMinimumSize(new java.awt.Dimension(1029, 70));
        TIP_UpperPanel_JPanel.setPreferredSize(new java.awt.Dimension(1029, 70));
        TIP_UpperPanel_JPanel.setLayout(new java.awt.GridLayout(2, 1, 5, 5));

        TIP_ThoiGian_JLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 24)); // NOI18N
        TIP_ThoiGian_JLabel.setText("Thời gian");
        TIP_ThoiGian_JLabel.setMaximumSize(new java.awt.Dimension(1029, 40));
        TIP_ThoiGian_JLabel.setMinimumSize(new java.awt.Dimension(1029, 40));
        TIP_ThoiGian_JLabel.setPreferredSize(new java.awt.Dimension(1029, 40));
        TIP_UpperPanel_JPanel.add(TIP_ThoiGian_JLabel);

        TIP_JSeperator.setMaximumSize(new java.awt.Dimension(1029, 10));
        TIP_JSeperator.setMinimumSize(new java.awt.Dimension(1029, 10));
        TIP_JSeperator.setPreferredSize(new java.awt.Dimension(1029, 10));
        TIP_UpperPanel_JPanel.add(TIP_JSeperator);

        add(TIP_UpperPanel_JPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator TIP_JSeperator;
    private javax.swing.JLabel TIP_ThoiGian_JLabel;
    private javax.swing.JPanel TIP_UpperPanel_JPanel;
    // End of variables declaration//GEN-END:variables
}
